---
execute: 
  freeze: true
---

```{r}
fp <- get_rehab_filepath()

library(readxl)
library(dplyr)
library(stringr)
library(lubridate)

raw_cases <- read_excel(fp, sheet = 2) |> 
  janitor::clean_names() |> 
  mutate(bid_open = bid_date - days(14), .before = bid_date) |> 
  arrange(bid_date)
```

# Bid Openings

::: {.panel-tabset}

## Upcoming

```{r}
upcoming <- raw_cases |> 
  filter(bid_open > today()) |> 
  slice_min(bid_open)
```

The next bid pack will be released `r format(unique(upcoming$bid_open), format = "%A, %B %d, %Y")` at 9:30 AM.

It will close on `r format(unique(upcoming$bid_date), format = "%A, %B %d")` at 9:30 AM.

## Active

```{r}
out_to_bid <- raw_cases |> 
  filter(project_status == "out for bid") |> 
  select(funding, street_name, bid_date) |> 
  mutate(funding = case_when(
    funding == "City" ~ "LOSB",
    .default = "EOC"
  ))
```

There are currently `r nrow(out_to_bid)` rehab projects out to bid:

```{r}
library(gt)

out_to_bid |> 
  gt() |> 
  tab_header(
    title = md("**Projects Currently Out to Bid**")
  ) |> 
  cols_label(
    street_name = "Project",
    bid_date = "Bid End Date",
    funding = "Contractors"
  ) |> 
  fmt_date(
    columns = bid_date,
    date_style = "yMMMd"
  ) |> 
  tab_options(table.width = "100%") |> 
  opt_row_striping()
```


## Most Recent

```{r}
most_recent <- raw_cases |> 
  filter(bid_date < lubridate::today()) |> 
  slice_max(bid_date) |> 
  select(bid_date, street_name, contractor, bid)

most_recent_date <- unique(most_recent$bid_date)
```

```{r}
most_recent |> 
  gt() |> 
  tab_header(
    title = md("**Most Recent Bid Opening**")
  ) |> 
  cols_label(
    street_name = "Project",
    bid_date = "Bid Date",
    contractor = "Contractor",
    bid = "Bid Amount"
  ) |> 
  fmt_date(
    columns = bid_date,
    date_style = "yMMMd"
  ) |> 
  fmt_currency(
    columns = bid,
    decimals = 0
  ) |> 
  tab_options(table.width = "100%") |> 
  opt_row_striping()
```


## Older

```{r}
older_bids <- raw_cases |> 
  filter(bid_date < most_recent_date) |> 
  select(bid_date, street_name, contractor, bid) |> 
  arrange(desc(bid_date)) |> 
  slice_head(n = 10)
```

```{r}
older_bids |> 
  gt() |> 
  tab_header(
    title = md("**Older Bid Openings**")
  ) |> 
  cols_label(
    street_name = "Project",
    bid_date = "Bid Date",
    contractor = "Contractor",
    bid = "Bid Amount"
  ) |> 
  fmt_date(
    columns = bid_date,
    date_style = "yMMMd"
  ) |> 
  fmt_currency(
    columns = bid,
    decimals = 0
  ) |> 
  tab_options(table.width = "100%") |> 
  opt_row_striping()
```

:::

::: {.callout-note}
The number of active rehab projects contractors can have at once has increased from 3 to 5.
:::
