project:
  title: "SCDH"
  type: website
  output-dir: _site
  execute-dir: project

website: 
  title: "SCDH"
  navbar: 
    left: 
      - href: index.qmd
        text: "Home"
      - href: contractors.qmd

theme: 
  light: flatly
  dark: solar
