project:
  title: "SCDH"
  type: website
  output-dir: _site
  execute-dir: project

execute: 
  echo: false
  message: false
  warning: false

website: 
  title: "SCDH"
  navbar: 
    left: 
      - href: index.qmd
        text: "Home"
      - text: "Contractors"
        menu: 
          - href: contractors/contractors.qmd
          - href: contractors/docs.qmd
          - href: contractors/lead-training.qmd
          - href: contractors/spec-manual.qmd
          - href: contractors/forms.qmd
    right: 
      - href: stories/index.qmd
      - href: research/index.qmd
      - icon: "book"
        menu: 
          - href: contractors/spec-manual.qmd
          - href: docs/policies.qmd
      - icon: "people"
        menu: 
          - href: about/team.qmd
          - href: about/offices.qmd

theme: 
  light: flatly
