project:
  title: "SCDH"
  type: website
  output-dir: _site
  execute-dir: project

execute: 
  echo: false
  message: false
  warning: false
  freeze: auto

website: 
  title: "SCDH"
  navbar: 
    left: 
      - href: index.qmd
        text: "Home"
      - text: "Contractors"
        menu: 
          - href: contractors/contractors.qmd
          - href: contractors/docs.qmd
          - href: contractors/lead-training.qmd
          - href: contractors/spec-manual.qmd
          - href: contractors/forms.qmd

theme: 
  light: flatly
