project:
  title: "SCDH"
  type: website
  output-dir: _site
  execute-dir: project

execute: 
  echo: false
  message: false
  warning: false
  freeze: auto

website: 
  title: "SCDH"
  favicon: logo.png
  navbar: 
    left: 
      - href: index.qmd
        text: "Home"
      - text: "Contractors"
        menu: 
          - href: contractors/index.qmd
          - href: contractors/docs.qmd
          - href: contractors/lead-training.qmd
          - href: contractors/spec-manual.qmd
          - href: contractors/forms.qmd
      - text: "Programs"
        href: programs/index.qmd
      - text: "Dashboard"
        href: projects/index.qmd
  page-footer: 
    left: "Shelby County Department of Housing"
    center: 
      - text: "Policies"
        href: about/policies.qmd
      - text: "LMI Map"
        href: about/LMI.qmd
    right: 
      - icon: github
        href: https://github.com/shelby-housing/shelby-repair
  body-footer: <script data-goatcounter="https://shelbyrepair.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

theme: 
  light: flatly
