---
title: "Welcome Home!"
---

The Shelby County Department of Housing helps to repair the homes of low-income homeowners in Memphis and Shelby County, TN through our home rehabilitation and lead programs. We also offer down-payment assistance to aspiring homeowners. [Click here to read more about our programs.](programs/index.qmd)

We are not currently accepting new applications for our home rehabilitation program.

---

<center>
# Neighborly Portals

We currently use Neighborly for accepting applications and bids for our rehab and lead programs. Please choose the appropriate sign-in page based on your role.

::: {.grid}

::: {.g-col-4}
<a href="https://portal.neighborlysoftware.com/SHELBYCOUNTYTN/contractor" role="button" class="btn btn-outline-primary">Contractor</a>
:::

::: {.g-col-4}
<a href="https://portal.neighborlysoftware.com/SHELBYCOUNTYTN/participant" role="button" class="btn btn-outline-primary">Participant</a>
:::

::: {.g-col-4}
<a href="https://portal.neighborlysoftware.com/SHELBYCOUNTYTN/administration" role="button" class="btn btn-outline-primary">Admin</a>
:::

:::

</center>

---

# Bid Openings

We regularly place rehab and lead projects out for bid to qualified contractors. Projects are bid out for two weeks through a sealed bid process.

::: {.callout-tip collapse="true"}
## New to Bidding?

We allow all contractors with a [valid EOC number](/contractors/docs.qmd#EOC) the opportunity to bid on our projects. However, additional documents are required for the bid to be accepted. If you are a contractor interested in working with us, please review the [required documents](/contractors/docs.qmd) for our program, create an account on [Neighborly](https://portal.neighborlysoftware.com/SHELBYCOUNTYTN/contractor), and upload these documents. Bids are conducted through Neighborly.

[Read an overview of our rehab process.](contractors/index.qmd)
:::

See below for current, upcoming, and previous bid openings for our rehab projects. Note that the tables below do not currently show projects for our lead program.

{{< include _partials/bids.qmd >}} 

Visit our [dashboard](projects/index.qmd) for more information on projects for the current planning year.
