---
title: "Required Documents"
toc: true
toc-title: "Sections"
---

Contractors will need the following documents to have their bids accepted:

- [ ] SAM Unique Entity ID
- [ ] Shelby County Business License
- [ ] TN Contractor License
- [ ] EOC/LOSB Number
- [ ] Certificate of Insurance
- [ ] EPA RRP Lead Firm Certificate
- [ ] TDEC Lead Firm Certificate (Lead projects only)

This page shows information on where to acquire each of the required documents. Click on "> View an example ..." to see an example image of each document.

---

### SAM Unique Entity ID {#SAMS}

SAM Unique Entity IDs are issued by the U.S. General Services Administration. To get a SAMs number, create an account for free at [sam.gov](https://sam.gov/). 

Click "Get Started" to create a new Unique Entity ID, or "Renew Entity" to renew an existing ID. When you submit a bid, your status must be "active".

::: {.callout-warning appearance="simple"}
When registering for an account, make sure to enable the option making your entity publicly searchable.
:::

<details><summary>View an example SAMs document.</summary>
  <embed src="../examples/SAMS.pdf" width="600" height="830" type="application/pdf">
</details>

---

### Shelby County Business License {#Shelby}

Shelby County Business Licenses are issued through the [County Clerk's Office](https://www.shelbycountytn.gov/559/Business-Tax-Division). Online applications are available [here](https://secure.tncountyclerk.com/index.php?countylist=79).

<details><summary>View an example Shelby County Business License.</summary>
<embed src="../examples/Shelby.pdf" width="600" height="830" type="application/pdf">
</details>

---

### TN Contractor License {#TN}

Tennessee Contractor Licenses are issued through the [TN Department of Commerce & Insurance](https://www.tn.gov/commerce/regboards/contractors.html).

Note that the ID Number listed on your Tennessee Contractor's License is the same as the GC Number (General Contractor Number) requested on Neighborly.

<details><summary>View an example Tennessee Contractor's License.</summary>
  <embed src="../examples/TN.pdf" width="600" height="830" type="application/pdf">
</details>

---

### EOC/LOSB Number {#EOC}

The [Shelby County EOC Office](https://shelbycountytn.gov/208/Equal-Opportunity-Compliance-EOC) issues Equal Opportunity Compliance (EOC) and Locally Owned Small Business (LOSB) Numbers. You do not need both an EOC and a LOSB number; an LOSB certificate qualifies as an EOC certificate.

Apply or renew your EOC license [here](https://apps.shelbycountytn.gov/EOCPublic/).

View the database of all active EOC numbers [here](https://apps.shelbycountytn.gov/EOCListings/welcome.xhtml).

Be sure to also register for a vendor number if you have not already.

<details><summary>View an example EOC/LOSB certificate.</summary>
  <embed src="../examples/LOSB.pdf" width="830" height="600" type="application/pdf">
</details>

---

### Certificate of Insurance {#COI}

A Certificate of Insurance can be created by contacting your insurance agent.

Below are the following policy requirements:

- **Comprehensive General Insurance**: $1,000,000 minimum per occurrence Commercial General Liability

- **Worker's Compensation Insurance**: $500,000 minimum

- **Automobile Liability**: $1,000,000 minimum on all owned, hired and non-owned autos

Please make sure the following information is entered by your agent:

::: {.grid}
::: {.g-col-6}

::: {.callout-warning appearance="minimal"}
## Certificate Holder
```
Shelby County Attorney's Office
Contract's Administration
160 N Main Street, Ste. 950
Memphis, TN 38103
```
:::
:::

::: {.g-col-6}
::: {.callout-warning appearance="minimal"}
## Description of Operations
"Shelby County Government, its elected officials, appointees, and employees will be named as additional insured."
:::
:::

:::

<details><summary>View an example Certificate of Insurance.</summary>
  <embed src="../examples/COI.pdf" width="600" height="830" type="application/pdf">
</details>

---

### EPA RRP Lead Firm Certificate {#RRP}

::: {.callout-important appearance="simple"}
The EPA RRP Certificate is required for **all projects**, lead or rehab.
:::

::: {.callout-important appearance="simple"}
## Notice to new contractors
An [EPA RRP Certificate](#RRP) will take at least a month to acquire.
:::

To get an RRP Certificate, you must first attend an [RRP training class](lead-training.qmd) by a state-certified lead instructor. Then, you must apply to receive the certificate through the EPA.

To get started, click "Apply Now" on the [EPA lead certification page](https://www.epa.gov/lead/getcertified).

Next, enter your firm name, phone number, and address to search for your firm in the database, even if this is your first time applying. If you are recertifying, your business should appear in the database. Select "Open" next to your firm's information, and select "Recertify Renovation firm (\$300 for 5-year certification)".

For new applicants, after searching in the database a link will appear below the search that says "Begin application to certify a 'New Firm'". A pop-up window will ask you which certification you wish to apply for. For an RRP certification, select "New Renovation firm (\$300 for 5-year certification)".

After selecting a certification and clicking "Continue", you will be directed to the **CDX Register/Log In** page. If you have previously used CDX, enter your username and password (or recover your information if you have forgotten your login.) If this is your first time, select "Register".

Users will then be asked to enter all states/territories where they plan to do renovation work. This page verifies that the EPA certification will allow you to do RRP work in that state.

New users will then be asked to enter their information to register for an account. Existing users can simply enter their job title and phone number in the information section. You can also select a firm already associated with your account, or you can choose "Associate a new firm with your account".

:::{.callout-warning collapse=TRUE}
## Application warning message
If you have submitted an application within the last 30 days, a warning message will appear. Select "I want to sign my previous application" to resume the application process. If you are taken to a page that says "You do not currently have any incomplete/outstanding submissions", your previous submission was successfully signed and no further action is required.

Select "I want to complete and pay for another application" to begin a new application if, for example, two branches of a business require seperate certifications. This option will require users to pay the full fee for a new application.

Select "Take me back to the EPA website" to exit the application.
:::

Next, users will be taken to the **Firm Information** page. For returning users, this section will be pre-populated. Verify the name and address, and enter an email and phone number.

For new users, search for your firm by entering at least three characters. If your firm is listed, select it and verify the information. If your business is not listed, click "Can't Find your Firm?" and select "Create My Own" to create a new firm. Please note that P.O. Boxes are not accepted for business addresses. You can enter a P.O. Box in the mailing address later in the form.

Once the form is completed, you will be sent an **email verification**. Click the link in the email to verify your email address and resume the application.

On the **Review and Payment** page, verify your information and edit if needed. Under the payment section, the total cost for certification will be displayed. Select a payment method and enter your payment information. For new users, you will be asked to enter the last four digits of your social security number for identity proofing. Provide the SSN of the person whose name is associated with the CDX account, and not the cardholder, if the two are different.

Under the certification section, read the terms and check both boxes. Then, select "Sign and Pay". You will be asked to enter your CDX password, and click "Continue".

A **"Processing Request"** popup will appear, and may take a few minutes to process. **Do not close this window** while the system is processing to avoid duplicate charges.

After the system has finished processing, you will see a page confirming that your application is complete and will be reviewed by the EPA. You will also receive a confirmation email from lead.paint@epa.gov.

Once the application is approved, the certificate will be emailed to the address on file. 

See our [lead training](lead-training.qmd) page for more information on RRP classes.

::: {.callout-important appearance="simple"}
The certificate submitted to us must be issued by the EPA. A certificate for completing the RRP training class is not sufficient.
:::

<details><summary>View an example EPA RRP Certificate.</summary>
<embed src="../examples/EPA.pdf" width="830" height="600" 
 type="application/pdf">
</details>

---

### TDEC Lead Firm Certificate {#TDEC}

::: {.callout-warning appearance="simple"}
The TDEC Lead Firm Certificate is only required for lead projects.
:::

Contractors must receive LBP Supervisor and RRP certification before applying for a Firm certificate. Lead Worker certification is not necessary for owners, but is required for those working for the firm.

After completing a lead training course, you must pass the State of Tennessee Commissioner's third-party certification exam within six months of completing the training course. The exam is administered online; see the [State of Tennessee's website](https://www.tn.gov/environment/toxic-substances-program/lead-hazard-program/lead-certification.html) for information on scheduling an exam. You must pass the exam with a 70% or higher.

After passing the exam, you must apply for firm certification with the State of Tennessee. Visit [their website](https://www.tn.gov/environment/toxic-substances-program/lead-hazard-program/lead-certification.html) for more information.

See our [lead training](lead-training.qmd) page for more information on classes.

<details><summary>View an example TDEC Lead Firm Certificate.</summary>
<embed src="../examples/TDEC.pdf" width="600" height="830" 
 type="application/pdf">
</details>
 
---

### Section 3 (optional) {#section-3}
Section 3 is a HUD requirement designed to ensure HUD funds invested in housing and community development activities provide employment opportunities for low-income persons.

Businesses that are owned by or significantly employ low- to very low- income residents are considered Section 3. Businesses can be considered Section 3 if they meet one of the following:

- 51% or more owned by Section 3 residents; or
- At least 30% of its full-time employees include current Section 3 residents, or were Section 3 within three years of the date of first employment with the business; or
- Provide evidence, as required, of a commitment to subcontract more than of 25% of the project award to subcontractors who meet the qualifications in the above two paragraphs.

A Section 3 resident is:

- A public housing resident; or
- A low- or very low-income person residing in the metro.

Below are HUD's low-income limits:

{{< include ../_partials/income-limits.qmd >}} 

Section 3 businesses will receive preference for contract opportunities on select federally-funded projects. Section 3 applies when these thresholds are met:

- Housing rehabilitation, housing construction, and other public construction projects where the total amount of assistance exceeds $200,000.
- Lead Hazard Control and Healthy Homes projects that receive at least $100,000 in assistance.

For reporting purposes, Section 3 information is collected even when projects are below these threshold limits.

---

### Minority & Women Business Enterprise (optional) {#MWBE}

A **Minority Business Enterprise (MBE)** is a business that is at least 51% owned and controlled by one or more minority persons.

A **Women Business Enterprise (WBE)** is a for-profit business that is at least 51% owned and controlled by one or more women who has been a resident of Shelby County for at least six months prior to the time of the application.

You can register as a M/WBE through the [EOC office](https://apps.shelbycountytn.gov/EOCPublic/).