---
title: "Rehab Process Overview"
toc: true
---

The Shelby County Department of Housing's (SCDH) home rehabilitation and lead programs offer assistance to qualified homeowners in need of repairs. Our inspectors visit their home and create a write-up of work to be done. These write-ups are posted on Neighborly and bid out to contractors.

The slideshow above offers an overview of our program and answers common questions.

```{=html}
<iframe class="slide-deck" width=100% height=400px src="presentation-2024-03-06/"></iframe>
```

Click on the slideshow above and use arrow keys to flip through the pages.

## Contractor Qualifications
All contractors with a [valid EOC number](docs.qmd#EOC) may bid on our projects. However, additional documents are required for the bid to be accepted. If you are a contractor interested in working with us, please review the [required documents](docs.qmd) for our program, create an account on [Neighborly](https://portal.neighborlysoftware.com/SHELBYCOUNTYTN/contractor), and upload these documents. Bids are conducted through Neighborly. 

<center>
<a href="https://portal.neighborlysoftware.com/SHELBYCOUNTYTN/contractor" role="button" class="btn btn-outline-primary">Neighborly Contractor Portal</a>
</center>

## Bid Awards
Bids are awarded to the lowest bidder. There is a cap of $36,000 for projects, and bids over 125% of the in-house estimate will also be rejected. If there are no valid bids for a project, it may be rebid up to 5 times. 

*For more information on bidding, see [Section XIV. Contractor Selection and Bid Opening for Rehabilitation Program](../about/policies.qmd#xiv.-contractor-selection-and-bid-opening-for-rehabilitation-program) of our rehab policies.* 

## Contractor Requirements
Homes must be brought up to code compliance. All items in the write-up must be completed per our spec manual. Contractors agree to a **five-year useful life & warranty on all major systems**. 

*For more information on work expected of contractors, see [Section XIII. Housing Rehabilitation Process](../about/policies.qmd#xiii.-housing-rehabilitation-process) of our rehab policies and review our [spec manual](spec-manual.qmd).*

## Contract Signing
Once a contractor has been awarded a bid, the SCDH will draft a contract. Contractors are asked to come to the SCDH offices to sign the contract. After the contract is signed by all parties, approved, and returned (a process which takes about a month), a pre-construction meeting will be set-up.


::: {.callout-important}
# Contractor Permit Requirements
- Contractors who have been awarded a project must have all permits in place at the time of the pre-construction meeting.
- Write-ups must be attached to the permit in Accela.
- Include **"SCDH Project"** in the permit label.
:::

*For more information on contracts and permits, see [Section XV. Award of the Construction Contract](../about/policies.qmd#xv.-award-of-the-construction-contract) of our rehab policies.*

## Inspections & Payment
Inspectors will conduct visits no less than once a week. The Department will authorize a **50% payment upon 75% completion of the work** for projects over \$5000 (projects at or below \$5000 will not have a partial payment). Payments will be issued upon receipt of the following:

- Invoice from the contractor to the SCDH requesting payment.
- Evidence of payment to licensed subcontractors who performed any completed permitted work.
- Signed copies of [Contractor Release of Lien](forms.qmd#contractor-lien-release) for all subcontractors performing permitted work.

*For more information on inspections and payments, see [Section XVI. Inspection, Close-Out, and Payment for Rehabilitation Work](../about/policies.qmd#xvi.-inspection-close-out-and-payment-for-rehabilitation-work)*

## Project Completion
Once work is completed, a **final inspection** will be carried out by an inspector, the contractor, and the homeowner. Once the SCDH has determined the job is complete, a Certificate of Completion and Final Inspection will be signed by all parties. This Certificate signifies that the job was completed in compliance with the contract and to the satisfaction of the homeowner. **At this time, the contractor will present all warranties to the homeowner.**

After this meeting, the contractor will file a **Notice of Completion** with the Shelby County Register of Deeds and return a certified copy to the SCDH. Upon receipt of the certified Notice, the SCDH will release final payment to the contractor.

*For more information on final inspections & payment, see [Section XVII. Final Payment](../about/policies.qmd#xvii.-final-payment)*

## Maximum Active Projects
Contractors may have up to **5 active rehab projects at a time**. If you have 5 active projects, your bids will not be accepted until an existing project is completed. A project is considered completed once the final payment has been billed.
