---
title: "Policies and Procedures"
subtitle: "Rehabilitation Program"
date-modified: "2023-10-12"
toc: true
toc-location: left
---

The following Departmental Policies and Procedures should be followed to certify and provide assistance to applicants under the Shelby County Department of Housing’s Rehabilitation Program.  Any questions related to waiving or altering these guidelines must be submitted for approval to the Department Administrator. 

These Policies and Procedures apply to any rehabilitation assistance provided under the THDA HOUSE Program, Community Development Block Grant (CDBG) Program, HOME Program, and any other rehabilitation programs administered by Shelby County Department of Housing.  Portions of these Policies and Procedures are used for the Lead Hazard Control and Healthy Homes Reduction Programs.  Both programs have their own Policies and Procedures, reference these policies as needed.  Rehabilitation programs operated by the Department of Housing are available to both owner-occupants and owners of rental property.

# Article I. Mission and Purpose

The Shelby County Housing Rehabilitation Program is established for the purpose of improving housing conditions for low and moderate-income families.  The housing rehabilitation program aids in the preservation of neighborhoods in Shelby County by correcting health and safety hazards and code violations.  These programs are available throughout the areas which are part of Shelby County’s Urban County Consortium and within City of Memphis limits with grant or alternative funding. The improvements made under this program result in neighborhood revitalization and housing stabilization.

# Article II. Objectives

1.	Reduction of unsafe and unsanitary housing conditions

2.	Neighborhood preservation

3.	Neighborhood reinvestment and community pride

4.	Improvement to low- and moderate-income owner occupants and rental property owners

5.	Correction of housing code violations

# Article III. Eligible Areas

All single-family properties located within the designated Urban County are eligible for assistance provided the occupants (owners occupied) meet the program requirements for participation.  Should funding sources become available to operate within the City of Memphis, eligible clients will be included in the program.

# I. Applicant Enrollment & Selection Criteria

A.	As needed to ensure adequate enrollment, Shelby County shall advertise the availability of the Rehabilitation Program in at least one newspaper that is of general circulation within Shelby County and online via the Department’s website. 

B.	Applications from individuals will be accepted during the open application window as determined by Shelby County based on available funding.  

C.	Applicants under Shelby County's Rehabilitation Program are considered eligible for assistance upon submission, verification and approval of all necessary documentation needed to fully determine client eligibility.

D.	In order to determine the order in which clients will be served, a needs-based assessment will be administered in order to serve more vulnerable segments of our community more effectively.  As additional funding becomes available additional eligible clients will be served.

E.	The needs-based assessment will follow the approved Vulnerability Index scoring criteria, attached as Exhibit A.

F.	Reserved For Future Use.

# II. Client Intake Process

1.	When the Client Intake staff starts to process a client’s application and discovers any required documentation is omitted, expired, or incorrect the Housing’s Client Intake staff will respond to the applicant in writing. The date of this letter is considered the start of the application process. This letter will include notification that their application has been received, as well as a list of any additional documentation necessary for them to be approved for assistance. The letter will also request documentation be returned to the Department of Housing within thirty (30) business days of the date on the letter.

2.	If the requested documentation has not been received at the end of thirty (30) days, Client Intake will issue a second letter requesting the documentation. The applicant has thirty (30) calendar days to provide said information or clear any problems preventing the Department of Housing from providing rehabilitation assistance, which may include but are not limited to or other documentation to verify eligibility, which may include but are not limited to income and mortgage verification, payment of taxes, items in collections, judgments, or other documentation to verify eligibility.

3.	Failure to provide requested documentation or clear existing liabilities within the 30-calendar day period will result in the applicant receiving a letter from Client Intake canceling their application.  The applicant may ask to have their file reopened within seven (7) days of receipt of cancellation and the Client Intake staff will verify if any changes have been made to determine if the application can be reopened.  

4.	If over six months has lapsed before a public bid opening is held or a contract is executed, the Client Intake staff will send the owner a Re-Verification Application and request updated income verification for all household members aged eighteen (18) or over.  

    a.	Income verification must be dated within six months of the execution of the contract.  Prior to routing a contract for execution, SCDH staff will confirm income verification falls within the previous six months.  If not, SCDH staff will secure documentation and verify income eligibility prior to routing the contract for signature.
    
5.	The Client Intake database will be kept current and reflect all actions taken during the approval process.

6.	Reserved for future use.

# III. Client Eligibility Requirements

The following general requirements must be met in order for Shelby County Department of Housing to provide rehabilitation assistance to an applicant.  

A.	The HOME Investment Partnerships (HOME) Program requires that participating jurisdictions (PJs) use one of two definitions of income:  Part 5 Annual Income; and IRS Adjusted Gross Income.  Effective, October 16, 1996, PJs were given the flexibility to choose one of the two definitions of annual income, Shelby County has elected to calculate income based on Part 5.  Projected gross income will be calculated rather than past earnings.

B.	The HOME regulations within 24 CFR 92.203(a) require that determining income eligibility must be accompanied by source documents (such as wage statements or interest statements) as evidence of annual income.  Third-Party Verification will be used (e.g., employer, Social Security Administration, or public assistance agency).  Although written requests and documentation is preferred, conversations with a third party are acceptable if documented through a memorandum to the file that notes the contact person, information conveyed, and date of call.  In addition, third party written verification by facsimile, email or electronic file transfer is permitted.  Documents provided by the applicant (e.g., pay stubs, tax returns, etc.) may be most appropriate for certain types of income and can be used as an alternative to third party verifications.  (Note, however, that if a copy of a tax return is needed, IRS Form 4506 “Request for Copy of Tax Form” must be completed and signed).  Client Intake staff will verify that documents collected satisfy all necessary income requirements, as supplied documents may not establish all income.  For instance, an employed applicant’s pay stubs may not provide sufficient information about the average number of hours worked, overtime, tips and bonuses.  In this case, it may be necessary to contact the employer to accurately project annual income.

C.	Given that the income limits are adjusted by household size, it is necessary to determine the size of the applicant household.  Some households may include persons who are not considered as family members for the purposes of determining household size and income eligibility, including:  foster children; foster adults; live-in aides; and children of live-in aides. A child who is subject to a shared-custody agreement in which the child resides with the household at least 50 percent of the time can be counted in the household.  Details on these exclusions are found in B. Exclusions. 

D.	Income verification must be re-calculated if the job does not start in six months from the date the funds are committed.  SCDH staff will verify income and source documentation is dated within six months PRIOR to routing a contract for execution.

    a.	Source documentation including periodic payment income such as social security is acceptable for the calendar year (see exception in section 4).
    
    b.	Source documentation must include two months of statements and be dated within six months of the executed contract.
    
E.	All applicants or beneficiaries of rehabilitation assistance are restricted to the full income guidelines established by the most current "Income Limits for Low-Income and Very Low Income Families", adjusted for family size; produced by the Department of Housing and Urban Development.  The income limits are updated annually and are available through HUD offices or on the Internet at https://www.huduser.gov/portal/datasets/il.html

## F. Income:

For purposes of rehabilitation activity, Annual Income is defined by the HOME regulations at 5.609(b) and as such requires the examination of source documents which include:

a.	The full amount, before any payroll deductions, of wages and salaries, overtime pay, commissions, fees, tips and bonuses, and other compensation for personal services. Two (2) months of source documentation evidencing annual income are required if currently employed (such as wage statement, interest statement, unemployment compensation statement).  

b.	Business Income:  Net income from a business or professions, i.e., self-employment income from own non-farm business; including proprietorships and partnerships.  Expenditures for business expansion or amortization of capital indebtedness cannot be used as deductions in determining net income; however, an allowance for depreciation of assets used in a business or profession may be deducted, based on straight line depreciation, as provided in Internal Revenue Service regulations.  Any withdrawal of cash or assets from the operation of a business or profession is included in income, except to the extent the withdrawal is reimbursement of cash or assets invested in the operation by the family.

c.	Interest and Dividend Income:  Interest dividends and other net income of any kind from real or personal property. Expenditures for amortization of capital indebtedness shall not be used as a deduction in determining net income. An allowance for depreciation is permitted only as authorized in paragraph b. Business Income above. Any withdrawal of cash or assets from an investment will be included in income, except to the extent the withdrawal is reimbursement of cash or assets invested by the family.

d.	Assets: 
    
    i.	Where the family has net family assets in excess of $5,000.00, annual income shall include the greater of the actual income derived from net family assets or a percentage of the value of such assets based on the current Passbook Savings Rate as determined by HUD (current passbook rate is 0.06%)
        
    ii.	Personal asset value is the real value of savings accounts, checking accounts, IRAs, mutual funds, other stocks, bonds or money market accounts, savings certificates and any other investment accounts, minus reasonable costs that would be incurred in converting assets to cash. 
        
    iii.	In general terms, an asset is a cash or non-cash item that can be converted to cash (note: it is the asset income earned – e.g., interest on a savings account – not the value of the asset – that is counted in annual income.)  An asset’s cash value is the market value less reasonable expenses required to convert the asset to cash, including penalties or fees for converting financial holdings, or costs for selling real property.  Under the rules, only the cash value (rather than the market value) of an item is counted as an asset.  If more than one person owns an asset, Department staff must prorate the asset according to the applicant’s percentage of ownership.  If no percentage is specified or provided by state or local low, assigned Department staff must prorate the asset evenly among all owners.  If an asset is not effectively owned by an individual, it is not counted as an asset.  
        
    iv.	Assets can generate income, and for the purpose of determining an applicant’s income, the actual income generated by the asset (e.g., interest on a savings or checking account) is what counts, not the value of the asset. The income is counted, even if the household elects not to receive it. For example, if an applicant elects to reinvest the interest or dividends from an asset, it is still counted as income. 
        
    v.	As with other types of income, the income included in annual income calculation is the income that is anticipated to be received from the asset during the coming 12 months. Several methods may be used to approximate the anticipated income from the asset. For example, to obtain the anticipated interest on a savings account, the current account balance can be multiplied by the current interest rate applicable to the account. Alternatively, if the value of the account is not anticipated to change in the near future and the interest rate has been stable, a copy of the IRS 1099 form showing past interest earned can be used.
        
    vi.	At least two months of source documentation will be collected for each of the household’s assets (checking accounts, savings accounts, etc.), to ensure any income from assets is accounted for, even if the family’s assets are below $5,000.
        
e.	Periodic Payment Income:  The full amount of periodic amounts received from Social Security, annuities, insurance policies, retirement funds, pensions, disability or death benefits, and other similar types of periodic receipts, including a lump-sum amount or a prospective monthly amount for the delayed start of a periodic payment (e.g., Black Lung Sick benefits, Veterans Disability, Dependent Indemnity Compensation, payments to the widow of a serviceman killed in action), except as provided in number 14 of Income Exclusions. An award letter will be provided showing the monthly gross amount will be used in verifying income. These forms of income verifications are acceptable for the entire calendar year.  If income is calculated in a calendar year and the job does not start until the next calendar year, a re-verification of income with the new amount will be required.  
    
f.	Unemployment and Disability Income: Payments in lieu of earnings, such as unemployment, disability compensation, worker’s compensation and severance pay, except as provided in number 14 of Income Exclusions.
    
g.	Welfare Assistance: Welfare assistance received by the family.  If the Welfare Assistance payment includes an amount specifically designed for shelter and utilities that is subject to adjustment by the Welfare Assistance agency in accordance with the actual cost of shelter and utilities, the amount of Welfare Assistance income to be included as income shall consist of:
    
    i.	The amount of the allowance or grant exclusive of the amount specifically designated for shelter or utilities; plus
        
    ii.	The maximum amounts the Welfare Assistance agency could in fact allow the Family for shelter and utilities.  If the family’s Welfare Assistance is ratably reduced from the standard of need by applying a percentage, the amount calculated under this paragraph is the amount resulting from one application of the percentage.		
        
h.	Alimony, Child Support and Gift Income:  Periodic and determinable allowances such as alimony and child support payments, regular contributions or gifts received from organizations or persons not residing in the dwelling.  Alimony and child support amounts awarded as part of a divorce or separation agreement are included as income unless the applicant certifies that the income is not being provided and takes all reasonable legal actions to collect amounts due; and 
    
i.	Armed Forces Income:  All regular pay, special pay, and allowances of a member of the Armed Forces (whether or not living in the dwelling) who is head of the family, spouse, or other person whose dependents are residing in the unit, except as provided in number 7 of Income Exclusions.
    
j.	All household members age eighteen (18) and over must have either income verified, or they must sign an Affidavit of Non-Employment stating that they do not receive any form of income.
    
## G. Exclusions:

Per the HOME regulations at 5.609(c):

a. Income of Children:  Income from employment of children, including foster children, under the age of 18 years. However, unearned income attributable to a minor (e.g., child support, TANF payments and other benefits paid on behalf of a minor) is included.
    
b. Foster Care Payments:  Payments received for the care of foster children or foster adults.  Foster adults are usually persons with disabilities, unrelated to the tenant family, who are unable to live alone.		
    
c. Inheritance and Insurance Income:  Lump-sum additions of family assets, such as inheritances, insurance payments, including payments under health and accident insurance and worker’s compensation, capital gains and settlements for personal or property losses, except as provided in 5 of Income Inclusions.	
    
d.	Medical Expense Reimbursements:  Amounts received by the family that are specifically for, or in reimbursement of, the cost of Medical Expenses for any family member.
    
e.	Income of Live-in Aides:  Income of live-in aides as defined in 24 CFR 5.403;
    
f.	Certain increases in income of a disabled member of qualified familied residing in HOME assisted housing or receiving HOME tenant-based rental assistance (24 CRF 5.671(a))	
    
g.	Student Financial Aid:  The full amount of student financial aid paid directly to the student or to the educational institution;
    
h.	Hostile Fire Pay:  The special pay to a family member serving in the Armed Forces who is exposed to hostile fire (e.g., in the past, special pay included Operation Desert Storm);
    
i. Self Sufficiency Income Program:  
    
    i)	Amounts received under training programs funded by HUD (e.g., training received under Section 3;
        
    ii)	Amounts received by person with a disability that are disregarded for a limited time for purposes of Supplemental Security Income eligibility and benefits because they are set aside for use under a Plan to Attain Self-Sufficiency (PASS);
        
    iii)	Amounts received by a participant in other publicly assisted programs that are specifically for, or in reimbursement of, out-of-pocket expenses incurred (special equipment, clothing, transportation, child care, etc.) and that are made solely to allow participation in a specific program;	
        
    iv)	Amounts received under a resident service stipend.  A resident service stipend is a modest amount (not to exceed $200 per month) received by a resident for performing a service for the owner, on a part-time basis, that enhances the quality of life in the project.  Such services may include, but are not limited to, fire patrol, hall monitoring, lawn maintenance, and resident-initiative coordination.  No resident may receive more than one such stipend during the same period of time. 
        
    v)	Incremental earnings and benefits resulting to any family member from participation in qualifying state or local employment training programs, including training not affiliated with a local government; and training of a family member as resident management staff.  Amounts excluded by this provision must be received under employment training programs with clearly defined goals and objectives, and are excluded only for the period during which the family member participates in the employment-training program.
        
j.	Gifts:  Temporary, nonrecurring, or sporadic income, including gifts; 
    
k.	Reparation Payments:  Reparation payments paid by a foreign government pursuant to claims under the laws of that government by persons who were persecuted during the Nazi era; (Examples include payments by the German and Japanese governments for atrocities committed during the Nazi era);
    
l.	Income From Full Time Students:  Earnings in excess of $480.00 for each full-time student 18 years old or older, excluding the head of household or spouse.
    
m.	Adoption Assistance Payments:  Adoption assistance payments in excess of $480.00 per adopted child.
    
n.	Family Support Act Income:  Does not apply to this program. 
    
o.	Social Security and SSI Income:  Deferred periodic amounts from Supplemental security income (SSI) and social security benefits that are received in a lump sum amount or in prospective monthly amounts.
    
p.	Property Tax Refunds:  Amounts received by the family in the form of refunds or rebates under state or local law for property taxes paid on the dwelling unit.
    
q.	Home Care Assistance:  Amounts paid by a state agency to a family with a member who has a developmental disability and is living at home to offset the cost of services and equipment needed to keep this developmentally disabled family member at home;
    
r.	Other Federal Exclusions:  Amounts specifically excluded by any other federal statute from consideration as income for purposes of determining eligibility or benefits under a category of assistance programs that includes assistance under any	program to which the exclusions of 24 CFR 5.609(c) apply.  A notice will be published in the Federal Register and distributed to housing owners identifying the benefits that qualify for this exclusion.  Updates will be published and distributed when necessary. including:
    
    vi)	The value of the allotment made under the Food Stamp Act of 1977 (7 U.S.C. 2017 [b]);
        
    vii)	Payments received under the Domestic Volunteer Service Act of 1973 (42 U.S.C. 5044 (g), 5058), employment through AmeriCorps, Volunteers in Service to America (VISTA), Retired Senior Volunteer Program, Foster Grandparents Program, youthful offenders incarceration alternatives, and senior companions;
        
    viii)	Payments received under the Alaskan Native Claims Settlement Act (43 U.S.C. 1626[c]);
        
    ix)	Income derived from certain submarginal land of the United States that is held in trust for certain Indian tribes (25 U.S.C. 429e);
        
    x)	Payments, or allowances made under the Department of Health and Human Services’ Low Income Home Energy Assistance Program (42 U.S.C. 8624[f]) (includes any winter differentials given to the elderly); 
        
    xi)	Payments received under programs funded in whole or in part under the Job Training Partnership Act (29 U.S.C. 1552[b]: (effective July 1, 2000, references to Job Training Partnership Act shall be deemed to refer to the corresponding provision of the Workforce Investment Act of 1998 [29 U.S.C. 2931] e.g., employment and training programs for Native Americans and migrant and seasonal farm workers, Job Corps, veterans employment programs, state job training programs, career intern programs, Americorps); 
        
    xii)	Payments derived from the disposition of funds to the Grand River Band of Ottawa Indians (Pub. L-94-540, 90 Stat. 2503-04); 
        
    xiii)	The First \$2,000.00 of per capita shares received from judgment funds awarded by the Indian Claims Commission, or the Court of Claims and the interests of individual Indians in trust or restricted lands, including the first \$2,000 per year of income received by individual Indians from funds derived from interests held in such trust or restricted lands (25 U.S.C. 1407-14008);
        
    xiv)	Amounts of scholarships funded under Title IV of the Higher Education act of 1965, including awards under the federal work-study program or under the Bureau of Indian Affairs student assistance programs,(20 U.S.C. 1087uu);
        
    xv)	Payments received under Title V of the Older Americans Act of 1985 (42 U.S.C. 3056[f]); e.g., Green Thumb, Senior Aides, Older American Community Service Employment Program;
        
    xvi)	Payments received on or after January 1, 1989, from the Agent Orange Settlement Fund or any other fund established pursuant to the settlement in the In Re Agent product liability litigation, M.D.L. No. 381 (E.D.N.Y.);
        
    xvii)	Payments received under the Maine Indian Claims Settlement Act of 1980 (25 U.S.C. 1721); 
        
    xviii)	Earned Income Tax Credit (EITC) refund payments received on or after January 1, 1991, including advanced earned income credit payments (26 U.S.C. 32[j];
        
    xix)	The value of any child care provided for or arranged (or any amount received as payments for such care or reimbursement for costs incurred for such care) under the Child Care and Development Block Grant Act of 1990 (42 U.S.C. 9858q);
        
    xx)	Payments by the Indian Claims Commission to the Confederated Tribes and Bands of Yakima Indian Nation or the Apache Tribe of Mescalero Reservation (Pub. L. 95-433);
        
    xxi)	Allowances, earnings and payments to AmeriCorps participants under the National and Community Service Act of 1990 (42 U.S.C. 12637[d]);
        
    xxii)	Any allowance paid under the provisions of 38 U.S.C. 185 to a child suffering from spina bifida who is the child of a Vietnam veteran (38 U.S.C. 1805); 
        
    xxiii)	 Any amount of crime victim compensation (under the Victims of Crime Act) received through crime victim assistance (or payment or reimbursement of the cost of such assistance as determined under the Victims of Crime Act because of the commission of a crime against the applicant under the Victims of Crime Act (42 U.S.C. 10602); and
        
    xxiv)	Allowances, earnings and payments to individuals participating in programs under the Workforce Investment Act of 1998 (29 U.S.C. 2931)

H.	Mandatory Deductions

    a.	Mandatory deductions. In determining adjusted income, the PJ must deduct the following amounts from annual income:
        
        i.	$480 for each dependent;
        
        ii.	$400 for any elderly family or disabled family;
        
        iii.	The sum of the following, to the extent the sum exceeds three percent of annual income:
            
                1. Unreimbursed medical expenses of any elderly family or disabled family; and
                
                2. Unreimbursed reasonable attendant care and auxiliary apparatus expenses for each member of the family who is a person with disabilities, to the extent necessary to enable any member of the family (including the member who is a person with disabilities) to be employed. This deduction may not exceed the earned income received by family members who are 18 years of age or older and who are able to work because of such attendant care or auxiliary apparatus; and
            
    iv.	Any reasonable child care expenses necessary to enable a member of the family to be employed or to further his or her education.

# IV. Immediate Cause for Non-Qualification

1.	Total investment will not exceed $36,000.00 once every five years exclusive of any necessary change orders or alternative funding sources available and eligible for the unit per section VII.3.(a) and VII.3.(b) below.  

2.	Total appraisal value including both land and improvement. For existing housing, HOME funds cannot be used if the after-rehab value of the property will exceed 95 percent of the area median purchase price for single family housing, as determined by HUD.

3.	If HOME funds are used, the value of the property after rehabilitation must not exceed HOME 2013 Final Rule published on July 24, 2013, §92.254 (a) (2) (iii), the HOME affordable homeownership limits provided by HUD for existing housing. (95% of the median purchase price adjusted annually).

    a.	The following calculation will be used to determine whether or not the unit exceeds this value: 
<center>Appraised Value after Rehabilitation<br>
Appraised Value + Rehab Cost = After Rehab Value</center>

4.	Applicants must agree to allow the Department of Housing to run a Title Search on the property to be assisted under the rehabilitation program.  Title Searches will be performed by the Client Intake staff. 

5.	Applicants with an existing mortgage on the home must also allow the Department of Housing to run a credit check to establish credit history.  No credit checks are required for applicants with no existing mortgage loan balance or liens on the property.

6.	Applicants will allow Shelby County to place a secure Deed Restriction on the property in “good faith”.  Debts cannot exceed income, property cannot be in foreclosure, and home mortgage payments cannot be in arrears over 60 days unless enrolled in a mortgage relief program. 

7.	The following are examples of “non-good faith” items that will prevent individuals from receiving assistance under the rehabilitation program:

    a.	Current enrollment in Chapter 13 Bankruptcy, must have permission from their US Bankruptcy Trustee.  Failure by the applicant not to get this approval will require the file to be canceled.  (Chapter 13 Bankruptcy dismissed on credit report indicates the bankruptcy was not accepted by the court and no approval is needed. Chapter 13 Bankruptcy discharged on credit report indicates all obligations have been met and they may be enrolled.)	

    b.	Current enrollment in Chapter 7 Bankruptcy, or having Chapter 7 Bankruptcy discharged within the last year;

    c.	Mortgage payments that are 60 days or more past due and not enrolled in a mortgage relief program or government refinance plan.

    d.	Delinquent court ordered judgments and liens related to the property, or any judgment related to the property of which applicant cannot provide documentation reflecting debt is paid.  Providing “good-faith” payment documentation from the Court is acceptable.   Exemptions are limited to liens placed by other non-profit or government rehabilitation programs.

    e.	Any form of tax lien or property involved in tax sale; 

    f.	If any municipal or County property taxes are delinquent, they must be under a payment plan and current on this plan;  

    g.	If taxes are over three years in arrears, they must complete the Shelby County Trustees HOME Financial Workshop and provide a certificate of completion and be current under a payment plan.

8.	Delinquent Shelby County Down Payment Assistance (DPA) loans. EXEMPT: Homeowner will have the opportunity to immediately reinstate the loan with fourteen (14) business days of notice. If the application is approved and the loan defaults at any time during the application process or after the approval will be ascended immediately.

9.	Reserved for future use.

# V. Unit Eligibility Requirements / Restrictions for Assistance

1.	In order for a unit to qualify as eligible under the rehabilitation program, the unit:

    a.	Must meet the following definition of dwelling unit: “a housing structure which is entirely for residential purposes, is designed for single-family use and fails to meet the minimum housing requirements as set forth in the Section 8 Housing Quality Standards, Southern Housing Code, or local	building codes.”
    
    b.	Must be located within a designated Shelby County Department of Housing service area (as determined by source funding).
    
    c.	Must not lie within a 100-year flood plain. EXCEPTION, to the policy on no work in a flood plain is if the home is still under a first mortgage and an escrow is being withheld for flood insurance on the home.  If the unit is insured through a mortgage escrow account which includes payment for flood insurance, work is allowed on the unit. If the home is paid in full they must have current flood insurance.
    
    d.	Must be a permanent component of local housing stock by its construction on a foundation (such as but not limited to pier and beam, crawlspace, or poured concrete) OR be considered a mobile or manufactured home with sufficient modifications to deem it a permanent structure.  In order to be considered permanent, the mobile home must not possess functioning wheels, axles, or trailer tongues.

2.	If a mobile or manufactured home meets the definition of permanent (1.d. above) the owner must also possess clear and original title of the unit.  The owner must also own the land on which the unit resides.

3.	Dwelling must be covered by a current Homeowner’s Insurance Policy.	

4.	The client requesting rehabilitation assistance must not have previously received The Department’s rehabilitation assistance in the past five years.  After five years has lapsed, the client can re-apply for additional rehabilitation assistance.

5.	If HOME funds are used for rehabilitation, the current appraised value of the unit must not exceed existing HOME 2013 Rule, §92.254 (a) (2) (iii) The HOME affordable homeownership limits provided by HUD for newly constructed housing and for existing housing. 

6.	If HOME funds are involved, the maximum property value after rehabilitation must not exceed 95% of the HOME affordable homeownership limits provided by HUD for newly constructed housing and for existing housing limits for Shelby County.	

7.	Reserved for future use.

# VI. Owner-Occupant Eligibility Requirements and Restrictions

1.	All applicants assisted under this category must be owner-occupants.	

2.	Owner-Occupants are defined as an individual(s) possessing title to an eligible property who permanently occupies the dwelling for residence.  A Title Search will be conducted by the Client Intake staff on each property to ascertain the validity of ownership on the property.	

3.	Ownership must be in the form of fee simple title, or a 99-year leasehold and the title must not have any undue restrictions or encumbrances that would unduly restrict the good and marketable nature of the ownership interest.	

4.	Owners listed on a title who do not occupy the residence and/or are no longer part of the household, must provide documentation that proves that they are not a part of the household.  Applicant must provide two (2) documents as proof of residency, i.e., service bills: utility, residential phone, notarized statement from landlord at present resident.

5.	All individuals listed on the title, mortgage, etc. will still be required to sign the assistance contract in order for the family/household to receive assistance under the rehabilitation program.

6.	Reserved for future use. 

# VII. Terms, Conditions and Consideration for Assistance

1.	The Shelby County Rehabilitation program is design to bring the assisted unit into codes compliance at the completion of the project.  Therefore, the amount of rehabilitation assistance that an applicant may receive will not exceed:		

2.	The actual and approved cost of the repairs and improvements necessary to make the dwelling unit conform to the housing standards adopted by the Department of Housing; and 

3.	The $36,000.00 assistance limit once every five years is established under these policies and procedures. This amount will include sewer hook-up fees.  Limits to lead base paint interim controls/ abatement and heathy homes reduction is found in the Lead Hazard Control and Healthy Homes Policies and Procedures.

    a.	EXCEPTION to the above cap:  In the event Shelby County’s Department of Housing receives special lead-based paint reduction funds, the amount of total assistance may exceed the $36,000.00 grant limit provided the increased cost is the result of lead-based paint reduction activity. This exception will apply only to a unit where a child who is under the age of six (6) resides or spends a significant amount of time at the residence.  Any costs associated with the reduction of lead hazards will be itemized through a separate write-up and will be considered lead reduction on the unit.  This amount will not be considered a rehabilitation cost and will be subject to any applicable lead reduction grant policies and procedures.
    
    b.	EXCEPTION to the above cap: In the event Shelby County’s Department of Housing receives grant funds from public or private sources that are eligible for home repairs, the amount of total assistance may exceed the $36,000.00 grant limit provided the increased cost is compliant with any relevant grant agreements or contracts from the respective funder.

4.	The maximum property value after rehabilitation for homeowner rehabilitation projects is as previously stated in Section IV. C and Section V. C.		

5.	All assistance will be secured through the Grant Note, Deed of Trust, and Restrictive Covenant in the total amount of the rehabilitation cost upon completion of construction work on the assisted unit.

    a.	Restrictive covenants will: Maintain a five (5) year forgiveness period with an annual forgiveness rate of 20% a year over the five (5) year period.  Past programs had a fifteen (15) year forgiveness period.  If the client was approved and had a 15-year lien secured on the property and five years has lapsed, the client can be approved for additional work and the new lien will also be placed on the property.

6.	In the event that a unit receives less than the $36,000.00 maximum in assistance, Shelby County will not consider additional assistance until five years has lapsed.  After five years, the client can reapply for assistance and if eligible receive additional rehabilitation assistance.	

    a.	The person requesting assistance after five years must fully reapply and meet all eligibility criteria.
    
    b.	The requested assistance must be at least five years after assistance originally provided.
    
    c.	The requested assistance must total more than $2,500.00.
    
    d.	The total new assistance must not exceed the $36,000.00 per unit cap, except if eligible for alternative funding sources as outlined in section VII.3.(a) or VII.3.(b) above.  
    
    e.	Upon completion of the new repairs the unit must be in codes compliance.
    
7.	In the event that a previously assisted homeowner is granted additional assistance, the amount of the new assistance will be reviewed under the assistance policies and will be added as additional liens on the property itself. NOTE:  All new assistance will result in extended property liens.  

8.	A new Grant Note, Deed of Trust, and Restrictive Covenant will be filed to cover the cost of the new repairs.

9.	If a homeowner that had previously applied and approved is no longer interested in receiving assistance, the unit can be cancelled and removed from the queue.  This confirmation process shall include initial verbal confirmation with the client (through the Site Inspector or Intake Coordinator) and subsequent follow-up through a written letter that will be both emailed and mailed with return receipt (certified mail) to the client.

10.	If a homeowner that had previously applied and approved is not responsive when the unit is ready for inspection, not making the unit accessible, and/or not honoring pre-set appointments, the unit can be cancelled and removed from the queue.  This confirmation will include notes from attempted contact, a copy of the letter sent to the homeowner that will be both emailed and mailed to the client providing them one week (or timeframe at the discretion of the Administrator) to respond, and a copy of the final cancellation letter with return receipt (certified mail).

11.	Reserved for future use.

# VIII. Grant Terms

1.	Forgivable Grant shall be for a fixed period of five (5) years (60 months).

2.	The Forgivable Grant will be forgiven at a flat rate of 20% per year over 5 years, i.e., \$10,000.00 grant balance will be reduced at a rate of \$2,000 per year. 

3.	Should the owner wish to have all liens on the property released prior to the grant term, said lien will be terminated upon full repayment of the outstanding balance of the grant.

    a.	EXAMPLE: \$20,000.00 is provided to rehabilitate a property; the term of the grant is 5 years.  Two years into the period, the owner wishes to have the liens removed from their property. Shelby County will release its liens upon repayment the grant note balance of \$12,000.

4.	No penalties will be assessed for early payoff of an outstanding grant note.

5.	Reserved for future use.

# IX. Grant Subordination

A.	A request may be made to allow the homeowner to refinance their mortgage and leave Shelby County in current position provided that the refinancing of the unit: 

    a.	Reduce the interest rate and/or the monthly payment (PITI) on the current mortgage, and provides cash or loan consolidation under the following stipulations;
    
    b.	Any cash out beyond the documented items caused by rounding is less than $500.00; and
    
    c.	In every case, the homeowner is put in a better financial position through a lower interest rate and/or lower monthly PITI payment.

B.	If the owner wishes to refinance and does not comply with all conditions as stated above, the full remaining balance shall become due and payable to Shelby County Department of Housing prior to the release of any and all held liens.

C.	Reserved for future use.

# X. Transfer and Repayment of Grants

A.	Should the individual homeowner sell his or her property prior to the completion of the grant forgiveness period, the remaining unforgiving balance of the grant must be repaid to the Department of Housing prior to, or at closing, and the release of the Restrictive Covenant.

B.	In the event of the death of a homeowner, the Department of Housing does not require repayment of the grant as long as the property passes to family member for permanent occupancy by an heir(s).  If the heir(s) sell or rent the property, or if the property is sold with monetary gain by any court action to settle outstanding claims or settle the estate, then the grant must be repaid less any forgivable portion.

C.	The following individuals are recognized as family members for purposes of the rehab program: husband, wife, son, daughter, father, mother, sister, brother, aunt, uncle, niece, nephews, father-in-law, mother-in-law, step-parent, step-brother, step-sister or a legally appointed foster parent or court appointed guardian. 	

D.	If the property is officially transferred to one of the above relatives, the appropriate Restrictive Covenants will be re-filed in the name of the heir and will run for the   balance of the original term.

E.	If they so choose, an heir may repay the appropriate unforgiven balance and have all restrictions removed from the property in question.

F.	Pay-off Requests will be completed by the Finance Manager and or the Program Manager.  The payoff amount will be sent to the requesting entity in writing and amount will be good for a 30-day period.

    a.	If payoff is received, a Deed of Trust Release will be prepared by the Client In-take staff 	at the request of the Finance Manager and will be submitted to the Division Director to approve and forward for execution by the Mayor’s office.  A letter stating that all obligations have been met and the details will be submitted with the release.
    
    b.	Once the release is received by the Department, the Client Intake staff will have it recorded at the Register’s Office and forward a copy to the payoff entity.

G.	Reserved for future use.

# XI. Other Grant Conditions

Specific terms and conditions are incorporated in the grant application and the contract documents.  These include but are not limited to:

1.	Allowing inspection by the Grantee, the federal government (HUD), and / or the State of Tennessee (THDA) of the property whenever it is determined that such an inspection is necessary.

2.	Furnish complete, truthful and proper information as needed to determine eligibility for receipt of rehabilitation assistance.  

3.	Sign a contract between the owner and contractor with conditions set forth in the document.	

4.	Reserved for future use.

# XII. Eligible Rehabilitation Activities

Rehabilitation assistance under Shelby County’s Rehabilitation Programs is designed to:

1.	Bring the condition of housing units occupied by eligible individuals into codes compliance, 

2.	Prevent existing units from falling out of the housing market in the future, and

3.	Directly address emergency needs of lower income households as they relate to housing maintenance.

In general, repairs under the Department of Housing’s Rehabilitation Program include any repairs necessary to bring the unit into local code compliance and/or pass HUD Housing Quality Standards.

Under the rehabilitation program, certain activities and situations are not considered eligible.  These activities are as follows:

A.	General Conditions:  In general, unless deemed an emergency repair necessary to correct a single health threatening code violation, in order to receive assistance under Shelby County's rehabilitation program, an eligible household must require a minimum of $2,500.00 in rehabilitation assistance in order to be considered eligible under the program.

B.	Remodeling:  The program is not designed to provide for the remodeling of a unit simply because an applicant meets the income criteria.  Unless remodeling is necessary to correct an existing problem within the structure, remodeling is not eligible under Shelby County's Rehabilitation Programs.  

C.	Remodeling includes, but is not limited to, items such as the addition of a new bedroom, bath, or other room within the unit; the installation of new cabinets when existing cabinet units are still completely functional; the installation of central air and/or heat when existing cooling and/or heating systems are adequate and operational; etc. 

D.	Remodeling is also interpreted as completing the necessary construction on a unit, either new or under renovation which an owner has started and never completed; or work designed to simply enhance the aesthetic quality of the home.

E.	Minor Home Maintenance:  Home maintenance of this type is allowable as part of a larger rehabilitation effort.

F.	Marketability Repairs:  Rehabilitation assistance which is designed to strictly increase the value of a home in order to make the unit more marketable or attractive is strictly prohibited. Rehabilitation assistance will not be provided on any unit which is listed on the market for sale, since such assistance is not deemed to be for the long-term benefit of the low-income family currently occupying the home.

G.	Luxury Repairs:  The repair of luxury items is strictly prohibited under Shelby County Rehabilitation Programs. Luxury items include, but are not limited to saunas, swimming pools, hot tubs, jacuzzies, etc.  Additionally, the installation of such items as part of rehabilitation is prohibited.

H.	Repair in a Flood Plain:  Rehabilitation assistance to low-income households living within the 100-year flood plain will not be provided under the rehabilitation program. unless the unit is approved under the exception criteria as outlined in V.A.3. of these policies.

I.	Extreme Deterioration:  Rehabilitation assistance on a property which has been abandoned by the homeowner due to condemnation, mandatory cut-off of utilities, a voluntary move, fire damage, or which would require the expenditure of funds in excess of the established rehabilitation limit is considered either a "new construction" or "reconstruction" project and is not eligible for assistance under rehabilitation programs.

J.	Historic Preservation activities are allowed as part of the rehabilitation process provided that the level of assistance on the historic unit does not exceed the established per unit level of assistance.

K.	Reserved for future use.

# XIII. Housing Rehabilitation Process

In general, the following activities will take place once an applicant has been deemed income eligible and has been fully approved by Client Intake for rehabilitation assistance.  

The following sections are a brief synopsis of the Department of Housing’s [Construction and Rehabilitation Specifications Manual](../contractors/spec-manual.qmd) and are intended to provide an overview of the rehab process.  For specific details addressing general contracting conditions and material specifications, please refer to the above-mentioned text. 

1.	Site Inspector for the Department of Housing will inspect the property for which a client’s application has been approved and will prepare a report that identifies each deficiency with respect to the housing code adopted by Shelby County and HUD Housing Quality Standards. 

    a.	The homeowner must provide adequate access to the home’s interior and exterior.  Should the Site Inspector deem the unit inaccessible for appropriate inspection, the homeowner will be given 30 days to make the unit accessible for inspection, or an adequate timeframe as provided by the Administrator of the Department that is reasonable to address such concerns.  A letter will be provided to the homeowner and should the unit remain inaccessible following the time provided the unit will be cancelled.
    
    b.	The homeowner may also submit a list to the Site Inspector itemizing requests for repair of items that may be eligible under the rehabilitation program.
    
    c.	If the house is built before 1978, a Lead Based Paint Inspection and Risk Assessment will be performed by the Site Inspector using an XRF, dust wipes, soil samples and paint chips as needed.  The inspection will follow all HUD and TDEC requirements, and comply with all notification procedures including providing the homeowner a copy of the lead safe booklet, a copy of the Lead Inspection and Risk Assessment (LIRA), and a copy of the clearance, as applicable.

2.	Upon inspection of the unit, the Site Inspector will inform the owner, whether or not in their opinion the unit will exceed the program limit for assistance. 

    a.	If the Inspector believes the unit will not qualify for assistance because it will   exceed program limits and in-house estimated costs exceed $50,000 to bring the property into codes compliance, they will notify their supervisor for cancellation of the project. The Construction Supervisor will ensure that the applicant is notified in writing that the unit will exceed the program limit for assistance due to the costs necessary to repair the home and that the unit is therefore ineligible for assistance.
    
    b.	If the unit does not require more work than the program allows, the Site Inspector will generate a work write-up and cost estimate based upon their inspection. This write-up will document all rehabilitation items to be carried out on the unit and will be reviewed with the homeowner prior to work being bid out. The homeowner will initial each page of the write-up as an indication that they are aware of the work to be carried out.

3.	The Site Inspector will prepare an estimate of each cost by line item. The cost estimate will be reasonable, reflect prevailing labor cost, and reflect a reasonable profit for the contractor.  Each write-up will:

    a.	Be detailed and specific in nature and will serve as a part of the specifications for the construction contract document;	
    
    b.	Include identifiable itemized cost in the work write-up, each itemized cost will be listed adjacent to the description of each rehabilitation item to be performed; and
    
    c.	Be written to comply and/or refer to departmental standards outlined in the [Construction and Rehabilitation Specifications Manual](../contractors/spec-manual.qmd) published by the Shelby County Housing Department.; and
    
    d.	Be written in compliance with Subpart J of the Lead Safe Housing Rule should the inspection reveal the presence of lead-based paint hazards.  This will include lead abatement measures (or interim controls on exterior hazards not disturbed by rehabilitation) should contracted amount exceed \$25,000.  If contracted amount falls between \$5,001 and \$25,000 any lead hazard reduction work will also be written to comply with abatement measures.  Safe work practices are always required and the unit must pass a lead clearance test following construction activities.

4.	An Environmental Review will be conducted and approved on all properties.  All levels of the Environmental Review will be completed prior to the commitment of any federal funds including HOME and CDBG.  

    a.	The written agreement accompanying the Environmental Review will be signed by the certifying officer and dated on or after the approved Environmental Review.

# XIV. Contractor Selection and Bid Opening for Rehabilitation Program

Note: Lead Hazard Control Program Policies are found in the Lead Hazard Control Policy and Procedures

Competitive Bid Policy: All jobs utilizing federal funds will be bid as a competitive bid.  

1.	The Department of Housing shall prepare all work specifications and documents as required by the rehabilitation program and will advertise the job to contractors currently on the contractor solicitation list.

2.	At the announced public bid opening, the Department of Housing shall require contractors in attendance to sign in. A member of the Department of Housing staff shall read each bid received by housing unit and prepare minutes of the bid opening. This information will be maintained on file at the Department of Housing.

3.	The lowest bid shall be the bid awarded, provided that the bid falls below $36,000 and does not exceed 125% of the in-house cost estimate as established by the Department of Housing, except when additional funding sources are eligible for the unit per sections VII.3.(a) or VII.3.(b) above.

4.	In order for the sealed bid to be feasible, the following conditions should be present:

    a.	Two (2) or more responsible bidders are willing and able to compete effectively for the business.
    
    b.	Bids must fall at or under 125% of the in house estimate AND adhere to any individual funding caps (such as Healthy Homes Supplemental funds or specific grant funds with distinct monetary caps) in order to be considered an acceptable bid, unless item (c) below applies.
    
    c.	Should a bid fall at or under 125% of the in house estimate but exceed a particular individual funding cap, the Administrator or their designee has the ability to negotiate an acceptable contractual amount and generate a change order to adjust the proposed contractual amount.
    
    d.	Reserved for future use.  

5.	If a discrepancy exists between the itemized lowest bid total and the sum of all line items bid amounts, the contractor will have the opportunity to accept the job for the lower of the two amounts.

6.	The Department of Housing will limit the total number of uncompleted jobs under contract that a contractor may acquire through the bid process to five rehabilitation projects, unless otherwise authorized by the Department Administrator.  Note the LBP Program also allows for five uncompleted jobs per contractor, unless otherwise authorized by the Department Administrator. 

7.	Any contractor selected must meet all Shelby County certification, licensing, and insurance criteria in order to be considered eligible for consideration on the unit.

8.	Any job that does not fall within the established parameters of the in-house estimate (See A.3.) will be re-bid, except if one of the conditions in item 3 or 4 above in section is true.

    a.	If after five bid openings, no contractor has submitted an acceptable bid, the job will be canceled and the Construction Manager will make sure the homeowner receives written notification of the cancelation.
    
    b.	Bid Acceptance of Last Resort.  The Department of Housing recognizes that it cannot assist every owner seeking assistance due to extreme costs and/or its current pool of certified contractors and will afford the following option to households with extreme high cost projects.

9.	In the event that the Department of Housing inspection indicates all work necessary to complete the project will clearly exceed the program limitations, the Department of Housing will allow the homeowner to take the following actions:

    a.	A work write-up will be provided to the homeowner that lists all work necessary.
    
    b.	The homeowner and the inspector will collaborate on the updated write up. 	
    
    c.	The job will be bid based on the new write-up.
    
    d.	Any contractor selected must meet all Shelby County certification, licensing, and insurance criteria in order to be considered eligible for consideration on the unit in question.	

10.	Reserved for future use.

LOSB Bid Policy: All jobs utilizing local funds only shall be subject to Shelby County’s current LOSB/WMBE goals. Homes funded through local sources shall adhere to the following bidding procedures:

1.	Bidding opportunities estimated to be below $50,000.00 in cost will be provided preferentially to Locally Owned Small Businesses (LOSBs) through the following methodology:

    a.	Shelby County Department of Housing (SCDH) will generate and utilize the Shelby County contractor mailing list of all eligible LOSB contracting companies
    
    b.	SCDH provide opportunity to provide quotes via email.
    
    c.	Contractors on the LOSB list will be encouraged to submit quotes and be given a period of two (2) weeks to provide total quote.
    
    d.	Quotes must be received by email from Contractor to SCDH staff.
    
    e.	Should no acceptable quote be received, the job will be placed in the subsequent solicitation to bid.
    
    f.	Should an acceptable quote be received, the job will be awarded to the eligible contractor with the lowest responsive bid, providing it falls between 80% and 125% of the in-house estimate.
    
    g.	SCDH will then email the appropriate Buyer in the Purchasing Department prior to routing the Contract to Contracts Administration and include a copy of this approval in the packet routed to Contracts Administration.
    
    h.	Reserved for future use.

2.	Contracts per SCDH’s existing rehabilitation program will be used to ensure agreements between the Contractor and the homeowner are secured.

    a.	Contract issuance will take place following the receipt of the PO sent from the Purchasing Department to SCDH.
    
    b.	Contract approvals will follow the same protocols as in place for the existing contract routing procedures, including securing original signatures from all three parties (Contractor, SCDH Staff, and homeowner(s)) and routing for the Mayor’s signature with associated encumbrance form and memo.
    
    c.	Notice to Proceed will be provided to the Contractor following receipt of the executed contract.
    
    d.	Reserved for future use.

# XV. Award of the Construction Contract

A.	The contract will become effective upon:

    1.	Verification of the low bid or quote. In the event line-item costs do not total the submitted bid total on the bid sheet, the contractor will be given the opportunity to honor the lower of the two prices.
    
    2.	Acceptance by the homeowner, the contractor, and Shelby County as evidence by the signatures of all parties on the contract, the expiration of the homeowner’s right of rescission period; and 
    
    3.	The issuance of a Notice to Proceed to the Contractor and the completion of a pre-construction conference to include contractor, homeowner, and site inspector.
    
        a.	The Contractor must provide evidence of all necessary permits (on paper or electronically) prior to or at the pre-construction meeting.
        
        b.	All permits must be pulled by the appropriately licensed contractor or subcontractor. The first sentence in the description of work on all permit applications must include “SCDH PROJECT” followed by a complete description of the nature of work in the write up relevant to the permitted line items.
        
        c.	The write up relevant to the permitted work must be uploaded to the Accela permitting system by the contractor at time of application. Any change orders that impact permitted work must also be uploaded to the permit and revisions made to the permit as applicable.
        
    4.	The Department of Housing will distribute the executed contract as follows: 
    
        a.	Original to The Department of Housing, copy to the homeowner, and a copy to the contractor. 	

B.	The fully executed contract shall include:

    1.	Rehabilitation Work Agreement
    
    2.	The Contract Proposal for Rehabilitation, which includes the work specifications (write-up) initialed by the homeowner(s)
    
    3.	Exhibit 2. Grant Note (page 9)
    
    4.	Exhibit 3. Deed of Trust (page 10)
    
    5.	Exhibit A: Description of the property
    
    6.	Exhibit 4: Restrictive Covenant and Terms of Contract Letter
    
    7.	Exhibit 5: Notice to Proceed
    
    8.	Exhibit 6: The Certification of Completion and Final Inspection.
    
    9.	Exhibit 7: The Right of Rescission
    
    10.	Exhibit 8: Sources and Uses of Funds
    
    11.	Exhibit 9: After Rehab Value Calculation
    
    12.	Change orders if necessary: Change orders are not approved until signed by the contractor, homeowner, inspector, and supervisor or other authorized management personnel.
    
    13.	Verification of Good Standing with HUD: An acceptable alternate worksheet for contractor certification regarding debarment, suspension, ineligibility, and voluntary exclusions for HUD Programs covered 24 CFR.
    
    14.	Contractor’s Non Kick Back Certification
    
    15.	Contractor’s Insurance and Certifications
    
    16.	Gratuity Form
    
    17.	Affidavit of Noncollusion
    
    18.	Section 3 Certification/Report
    
    19.	Drug Free Workplace Affidavit
    
    20.	Jobs Created Report
    
    21.	Section 3 New Hire Questionnaire
    
    22.	If at or over $30,000: Must include Federal Funding Accountability and Transparency Act (FFATA) Data Reporting Requirement
    
    23.	Bid Sheet

C.	Reserved for future use.

# XVI. Inspection, Close-Out, and Payment for Rehabilitation Work

Inspection of construction on rehabilitation projects will be performed by the Department of Housing staff as follows: 

1.	Initial inspection will include a brief assessment and cost estimate of all major systems to determine unit eligibility and whether a full work write up is warranted.

    a.	Initial inspection will also include an assessment of whether there are any life threatening deficiencies.  The Rehabilitation Specification Manual outlines agency referral protocols, as applicable.

2.	Compliance inspections will be made as often as necessary, but no less than once per week, to assure the work is being performed in compliance with work specifications and other related state or local laws and ordinances.

    a.	All compliance inspections will be documented in the centralized data management system in use by the Department.

3.	Written documentation of inspections will be filed on each unit receiving assistance and a copy will be provided to the contractor. This documentation will include the date and time of inspection, as well as a description of the activity taking place at the time the inspection was conducted.

4.	A final inspection will include an assessment of whether all major systems an expected 5-year lifespan.

5.	The Department of Housing will allow partial payments.

    a.	The Department will authorize a 50% payment upon 75% completion of the work for jobs awarded at \$5,001 to \$36,000, or cap as determined in consideration of alternative funding sources as outlined in section VII.3.(a) or VII.3.(b) above. Jobs \$5,000 and below will not receive a partial payment.

6.	Payments will be issued following the receipt of all required documentation from the contractor including:

    a.	Invoice from contractor to Shelby County Department of Housing requesting payment.
    
    b.	Evidence of payment to licensed subcontractors that performed any completed permitted work.
    
    c.	Signed copies of Contractor Release of Lien for all subcontractors performing permitted work.

7.	Other payments may be authorized by the Administrator or Deputy Administrator upon recommendation of the Construction Manager and/or Site Inspector; however, no contractor will receive more than two total draws per contract.

8.	Lead Hazard Control and Healthy Homes Supplemental Fund Program jobs will not receive a partial payment.

9.	Reserved for future use.

# XVII. Final Payment

1.	Upon completion of the rehabilitation work, a final inspection will be carried out by the Department of Housing, the contractor, and the homeowner. Barring situations beyond anyone’s control, all parties should be present at the time of the final.

2.	Inclement weather is an extreme weather condition, such as snow, ice, flooding, tornado, or hurricane that prevents or delays routine travel.  This also includes wind speeds exceeding 20 miles per hour.  All project delays due to inclement weather, material delivery, etc must be approved by the Program Manager.  This request must be made in advance or the day of request.  Requests made after the day in question, will not be approved. 

3.	Once the Department of Housing has determined the job is complete, a Certificate of Completion and Final Inspection will be prepared.

    a.	This Certificate, signed by the homeowner, contractor, and Department of Housing representative, will signify that the job has been completed in compliance with all contractual components and to the satisfaction of the homeowner.

4.	At this time, the contractor will present all warranties to the homeowner.

5.	Upon completion of work performed, the contractor shall file a Notice of Completion with the Shelby County Register of Deeds and return a certified copy to the Department of Housing.

6.	Upon receipt of the Notice of Completion, the Department of Housing will release final payment to the contractor.

7.	In the event of complaints from subcontractors concerning non-payment for services rendered, the Department of Housing will require a release of liens from all subcontractors prior to the release of final payment. 

8.	If the homeowner refuses to sign the final acceptance certification upon completion, Shelby County will authorize full payment for those items which are undisputed by all parties and which have not been agreed to in writing by both the contractor and homeowner(s).

9.	Any other items shall be paid upon completion of the established Grievance Procedures.

10.	All work carried out is warranted by the primary contractor for a period of one year from the date of final inspection against any material defects and normal wear and tear.

11.	The Deed of Trust, Restrictive Covenant and Grant Note will be recorded at the Shelby County Register’s office and noted in database so that it can be released with the forgiveness period expires. The Client Intake staff will keep the database current with recorded liens and monthly prepare releases and forward to The Division Director who will have the releases executed.  Once returned, the Client Intake staff will have the releases recorded and not the release information in the database.

# XVIII. Solicitation and Enrollment of Contractors

A.	The Department of Housing will announce the rehabilitation program and contractors enrollment in conjunction with public hearings or as needed throughout the year via public announcements in local newspapers in an effort to openly recruit eligible contractors for rehabilitation activities.  

B.	These meetings will be used to create a contractor solicitation list whereby interested contractors will be notified in writing of the Department of Housing bid opportunities. New contractors are also encouraged to contact the Department of Housing with any questions regarding bid opportunities, vendor registration, Section 3, or to be a member of the solicitation list.

C.	The Department will publish each bid package in a local newspaper announcing the opportunity to bid on rehabilitation projects and at the same time will notify all contractors on the contractor solicitation list, in writing, of the available bid package.   This notification will specify the date on which bids are due as well as time and place of the public bid opening on rehabilitation projects.

D.	Contractors not submitting bids during two consecutive bid opportunities will still be able to bid on Department of Housing jobs; however the contractor will not receive direct mailings from the Department until a bid has been submitted. 

E.	It will be the responsibility of the Contractors who fall into this category to monitor public notices or call the Department to inquire about bid opportunities. 

F.	The Department of Housing will maintain records of all bid openings and contract awards.

G.	All contractors participating in Shelby County rehabilitation activity shall be required to maintain on file with Shelby County proof of all applicable insurance policies, a copy of their home improvement or general contractors license, proof of current Equal Opportunity Compliance Number or Locally Owned Small Business (LOSB) as issued by the Shelby County Equal Opportunity Compliance Office, and his / her Shelby County business license.  

H.	All contractor information must be current and up to date prior to awards of a competitive bid.

I.	Contractors who will be deemed ineligible to participate in the rehabilitation program are those who: 

    a.	Are on the Federal Debarred list;
    
    b.	Have not paid for materials or supplies in a timely manner;
    
    c.	Have failed to complete three (3) rehabilitation jobs within the allotted time frame as specified by the rehabilitation contracts; and/or
    
    d.	Have failed to provide the Department of Housing with a valid business address, operational phone number, and/or have refused to accept official correspondence.

J.	Reserved for future use.

# XIX. Policy on Small Business Enterprises (SBES), Minority Business Enterprises (MBES), and Women Business Enterprises (WBES) and Section 3 Contractors

A.	In cooperation with Shelby County Purchasing Department and Shelby County Equal Opportunity Compliance Office, the Department of Housing will encourage local small businesses to become certified as Locally Owned Small Businesses (LOSB’s) by Shelby County.	

B.	The LOSB designation is designed to benefit SBE’s, MBE’s, WBE’s, and Section 3 Contractors operating in Shelby County.	

C.	Beyond the LOSB designation, the Department of Housing will work closely with both Equal Opportunity Compliance Office and Purchasing Department, to make certain the opportunity to bid on Department of Housing projects reaches as many MBE’s, BE’s and Section 3 Contractors as possible.

D.	Shelby County encourages the participation of Section 3 contractors in all of its rehabilitation projects and publishes this encouragement as part of the advertised bids.

E.	During contractor solicitation meetings, contractors will be encouraged to join the HUD Section 3 Business Registry if their business meets the definition of a Section 3 Business Concern.

F.	Reserved for future use

# XX. Special Contractor Requirements

All Rehabilitation Programs:

A.	It is mandatory that any contractor participating in the rehabilitation program provide   the Department of Housing with a current, up-to-date and operational phone number and/or email address where they can be reached at all times during normal business hours. Contractors must notify the Department of Housing whenever the phone number or email address changes. Failure to maintain an operational phone number with the Department of Housing is grounds for suspension and/or termination from the program.

B.	Contractors wishing to speak to a specific Housing Department employee on a specific issue should request a set appointment. A walk-in visit does not guarantee appointment will take place.

C.	When dropping off requested information, it is the contractor’s responsibility to obtain a receipt for any information the contractor leaves with a Housing Department employee. In the event a contractor is submitting any required information, such as contract(s), invoice(s) or highly important information, to prevent miscommunication, request of a receipt is suggested.

## Lead Based Paint Activities:

A.	Contractors are required to always have a State of Tennessee Certified Supervisor on site or within thirty (30) minutes from the site during any activity associated with lead hazard reduction work. 	

B.	Any lead contractor who fails three clearance test on three separate jobs during any twelve (12) month period will be immediately suspended from bidding on lead hazard reduction projects for a period of six months.

C.	Further details can be found in the Lead Hazard Control Program Policies and Procedures.

# XXI. Contractor Suspension and Termination

A.	In general, the Department of Housing will follow procedures established by the Shelby County Purchasing Department should the need arise to terminate a contractor from the Department of Housing rehabilitation projects.  However, given the nature of the work carried out, i.e., work in and on occupied residences of Shelby County citizens, the need to suspend or remove a contractor from a project may occur.  

B.	In the event that conflicts between the homeowner and contractor arise, or repeated problems with a contractor’s work occurs, cancellation of a project and / or the suspension of a contractor may be carried out as follows:

a.	Homeowner Termination of Contract: The homeowner may terminate the contract at any time for cause.  Said termination will be carried out upon receipt of written notification to the Department of Housing by the homeowner.  Such a request must include the reasons for requesting contract termination. 
    
    i.	EXAMPLES of grounds for termination include: failure to supply properly skilled workman, failure to provide proper materials, destruction of homeowner property by the contractor or others they employ, etc.
        
    ii.	Should the homeowner terminate a contract for cause, the Department of Housing will evaluate all work completed up to date of contract termination, and Contractor shall be paid for all work completed at that time.  Payment for completed work will be based upon the line item bids submitted to the Department of Housing by the Contractor during the bid process.
        
b. Suspension/Termination by the Department of Housing: It is the Department of Housing’s responsibility to ensure all contractors participating in rehabilitation and lead reduction programs carry out work in an acceptable manner.  This includes both professional work practices and acceptable quality of workmanship.
    
    i. Since contractors are working in homes of the public, professional work practices and standards must be clearly enforced.  The Department may suspend/terminate a contractor from participating in the bid process for problems that result in unsatisfactory workmanship practices and unprofessional behavior on the job. 
        
    ii.	Contractors may be suspended or terminated at any time based on the severity of the problem and upon completion of their appeal, should they elect to exercise their right to the appeal process.
        
    iii.	EXAMPLES of cause for suspension/termination include but are not limited to, supplying false or inaccurate information, not maintaining a working phone number on file with the Department of Housing, repeatedly failing to complete contracts on time, violations of contract agreements, unprofessional workmanship, and failure to pay subcontractors and materials suppliers and failure to complete warranty work, etc.

C.	Contractors listed on a Federal, State, or Local Debarment or Suspension list will automatically be terminated from participating in bids issued by the Department of Housing.

D.	Suspension/Termination Process: Should the need arise to suspend or terminate a contractor, the following procedures will be used:

    a.	The Department of Housing will notify the contractor in writing, that their firm is being considered for suspension/termination from the department’s programs.  This letter will specify the reasons that suspension/termination is being considered and will be sent certified mail.
    
    b.	During this process, the contractor will not be allowed to bid on any additional work with the Department of Housing, nor will he/she be allowed to start any new jobs that may have been awarded to his / her firm.
    
    c.	Failure to accept certified mail or respond to a certified letter, are grounds for immediate suspension of the contractor.
    
    d.	The contractor will be allowed to appeal their suspension or termination within ten (10) days of the date when the letter is received by their firm.
    
    e.	Should the contractor wish to appeal the suspension or termination, they will request and attend a meeting with a review committee which will include a representative from the Department of Housing, Shelby County EOC, and a member of the Purchasing Department.  
    
    f.	At this meeting, the contractor will be asked to present reasons that suspension or termination from the Department of Housing programs is not justified.	
    
    g.	The committee will evaluate the evidence and a response will be issued, via certified mail, to the contractor within seven (7) days of the appeal.
    
    h.	The decision for suspension or termination of a contractor, by this committee, is final.  Suspension from the program can be for up to twelve months.  Any action that would exceed this period of time will follow the Shelby County Purchasing Department’s Policies and Procedures for Disqualification
    
    i.	If a decision to suspend or terminate is upheld by the review committee, all jobs and/or contracts not yet underway will be forfeited and ultimately re-bid.
    
    j.	Should the need arise to terminate an existing contract due to justifiable cause the contractor will be paid only for those items that are 100% complete at the time of the suspension or termination

E.	Reserved for future use

# XXII. Grievance Procedure

Disputes between homeowner and contractor may arise from time to time during the life of a rehabilitation project. In these instances, where mutually satisfactory agreement cannot be reached between the parties, the Grievance Procedure will be followed. With respect to issues relating to policies, procedures, and or performance on a contract associated with the rehabilitation program:

1.	The grievance by the homeowner or contractor is to be filed, in writing; with the Department of Housing.

2.	The Construction Manager and Site Inspector will schedule a meeting with all parties involved in an effort to resolve the problem. The results of this meeting will be documented in writing and included in the job file.

3.	In the event, the Construction Manager and Site Inspector are unable to resolve the conflict, the Department Administrator or a designee; will meet with the homeowner and contractor and in an effort to negotiate a solution.

4.	Should these efforts fail, the Department Administrator will forward the complaint, including documentation of his / her attempts to resolve the situation to the Division Director or the appropriate County Officials who will make a determination on the complaint.

5.	At all points of this process, the contract and rehabilitation specifications, along with the HQS evaluation of the unit will provide the basic documentation by which the relative merits of any dispute will be judged.

6.	Upon final determination of the dispute, all debts to the contractor will be paid or denied in accordance with the final determination. The final decision will be documented in writing and placed in the project file.

7.	Reserved for future use.

# XXIII. Conflict of Interest

A.	No elected or appointed Federal, State or Local official, member of the local governing body, or any other public official or employee who exercises any functions or responsibilities in conjunction with administration of the Housing Rehabilitation program will have any interest, direct or indirect, in the proceeds or benefits of the rehabilitation program.  

B.	Reserved for future use.

# XXIV. Kickbacks and Discounts

A.	No member of the governing body of the Grantee or any Grantee employee will receive kickbacks or discounts from either contractors or property owners in return for special favors in regard to housing rehabilitation.  A Non-kickback Certification will be signed and part of the contract. 

B.	Reserved for future use.

# XXV. City of Memphis and Shelby County Coordination

A.	This section outlines points of coordination between the City of Memphis and SCDH if alternative sources of funding from the City of Memphis are available and executed agreements are in place.

B.	All coordination will take place between designated points of contact identified by and mutually agreeable to the City and SCDH.

C.	All documents and file sharing will be centralized into secure cloud-based software programs and maintained and organized by SCDH staff.  Access to all applicable documents will be provided to City representatives as needed and/or requested.

D.	Housing rehabilitation work coordinated between the City and County will be subject to all relevant federal guidelines, regulations, and statutory requirements as established by the funding source (i.e. HOME, CDBG, or others as applicable).

E.	All communication with homeowners and contractors will be managed and conducted by SCDH staff.

F.	Client Intake:

    a.	If six months or more has lapsed between income verification and contract execution, SCDH will re-certify clients for income eligibility.
    
    b.	Upon recertification, SCDH will provide documentation using the HUD CPD Calculator that clients are eligible to receive services.
    
G.	Section 3:

    a.	SCDH will continue advertising Section 3 business opportunities and encouraging Section 3 participation in all relevant programming.
    
    b.	SCDH will document any advertisements, letters, or outreach efforts and provide to the City as relevant to capture efforts to encourage Section 3 business opportunities.

H.	Environmental Review:

    a.	No contract can be executed nor can work can begin on any property prior to receiving an approved environmental review from the City.
    
    b.	SCDH staff will submit necessary information to City staff to initiate and complete the Environmental Review process.

I.	Inspections and Work Write Ups:

    a.	SCDH staff will coordinate, at a minimum or as required, three (3) inspection visits during each job:
    
        i.	SCDH will ensure City personnel are available to attend initial inspections that generate the Initial Work Write Up Assessment.  Initial Work Write Up Assessments will take place following the Lead Inspection and Risk Assessment as required for pre-1978 homes.
        
        ii.	SCDH will ensure City personnel are available to attend at least one progress inspection during the construction phase of the job.
        
        iii.	SCDH will ensure City personnel are available to attend the final inspection and secure signatures of all parties on the Notice of Completion.
        
    b.	Work Write Ups will address all requirements of CFR 92.251 as applicable to HOME property standards and codes compliance measures.
    
    c.	City will review Work Write Ups for cost reasonableness and approve or identify any changes required.

J.	Procurement/Bidding Process:

    a.	Procurement and award of sealed bids will follow the existing procedures set forth in Section XIV of these Policies and Procedures.
    
    b.	SCDH will check the federal debarment list for each awarded job and evidence of results demonstrating each contractor recommended for award is not debarred will be included in the master file.
    
    c.	SCDH will submit confirmation of awarded jobs for City review.
    
    d.	Once awarded to an approved contractor, City will issue a Notice to Proceed if all Environmental Reviews are complete and all parties are prepared to begin work on the property. SCDH will then issue a Notice to Proceed to the contractor to begin work.

K.	Close Out and Invoicing:

    a.	City will provide approval signatures on the Notice of Completion and Final Inspection forms.
    
    b.	SCDH will invoice City for eligible expenses for units served, excluding all required match as applicable.
    
    c.	Payment requests will include:
    
        i.	Invoice from SCDH to City with requested amount, sources of funds (including match as applicable), and SCDH signature.
        
        ii.	Copy of invoice from selected contractor to SCDH, including both partial and final payment invoices as applicable.
        
        iii.	Copy of SCDH Purchase Order.
        
        iv.	Copy of both approved and signed Notice of Completion and Final Inspection forms.
        
    d.	Note that all program income will return directly to the City’s Division of Housing Community Development as described in the respective Grant Note.  Additionally, match funds will be recovered as described in the same Grant Note by the City of Memphis and not by Shelby County should any program income be generated from resale or refinancing.

L.	Reserved for future use.
 
# Exhibit A: Vulnerability Index
## Purpose
In the past, the Shelby County Department of Housing’s Home Rehabilitation Program accepted applications on a first-come-first-served basis. The purpose of the Vulnerability Index is to instead rank applications based on need, so the department can better target funds and resources to homeowners who are in greatest need.  This approach focuses on a more equitable system of client intake such that more vulnerable clients are prioritized, and allows those with fewer resources to better access government services.

## Methodology
To determine need, a variety of factors will be considered.

-	Income. Currently, the program is limited to households with low-to-moderate incomes. Those on fixed incomes, such as Social Security and checks for disabilities, have fewer resources available to pay for repairs than households with occupants who are gainfully employed or have additional income from other sources.

-	Age. Homeowners who are senior citizens might struggle more than younger homeowners to complete repairs and maintain the property. Failure to maintain a property can cause a home’s quality to rapidly deteriorate. The age criterion is meant to ensure elderly individuals have healthy, quality housing which allows them to continue living in the home.

-	Assessed value. While homes with high assessed values might have a higher housing cost burden for low-moderate households, these homes are typically newer and in better condition than homes with lower assessments. Currently, HOME rules stipulate that funds may not be used to repair homes appraised over $251,000 (FY21); homes will be ranked based on a percentage of this value.

-	Housing cost burden. Housing cost burden is the percentage of income that a household spends on housing, including the cost of mortgage, insurance, and utility payments. Households that have a higher cost burden will have less income to save and spend on home repairs.

-	Repair needs. The type of repairs a homeowner needs can significantly affect the resident’s quality of life. As of July 1, 2022, the program now asks applicants if they have any of the following problems with their home:

    - Broken AC/Heater
    - Holes in roof
    - Damaged/rotten exterior
    - Damaged/rotten flooring
    - Lack of adequate plumbing facilities
    - Electrical problems
    - Broken/unsealed windows and/or doors
    - Need for disability accommodations

    This list was created by examining the most common urgent problems, consulting with inspectors to determine which problems are considered the most serious for homeowners and referencing the Healthy Homes Rating System.

-	Percentage Low Income. Where a home is located also factors into the need for services.  If a homeowner lives amongst greater percentages of lower income residents, it is more likely that the area would benefit from investment and services.  This helps revitalize areas and neighborhoods that are likely lacking capital to maintain and improve homes.  Scoring will therefore include the percentage low- to moderate-income households in the census tract where a client is located.

Applicants will be rated using the above factors using a points system, detailed below. Applicants with the highest number of points will be prioritized for services.  All information is either captured during the intake process or gathered from existing census data.

## Point Designations
Given the factors outlined in the above methodology section, the following point values will be assigned to each case (see Table 1).

Income guidelines are based on the current year’s Income Limits Documentation System.  Applicants in the July 1-August 31, 2022 pool are scored on FY22 limits.  Age is verified with date of birth on a valid form of identification submitted with the application.  Assessed home values are determined through verification from Shelby County Assessor’s current database.  Assessed home value percentages are then calculated based on the maximum HOME Investment Partnerships Program Homeownership Value Limits for the current year.  Repair needs are self-reported on the initial application and verified by site inspection prior to receiving assistance.
 
Table 1. Point values for each identified vulnerability criteria.  Note each criterion is not weighted equally as outlined in the narrative below.

| Point Value |	0 |	1 |	2 |	3 |	4 |	5 |
|---|---|---|---|---|---|---|
| Income	| >80% AMI	| 50-80% AMI	| 30-50% AMI	| 20-30% AMI	| 10-20% AMI	| 0-10% AMI |
| Age	| -	| < 50	| 50-65	| 65-75	| 75-80	| 80+ |
| Assessed Value	| 100+-80% HOME	| 65-80% HOME	| 50-65% HOME	| 35-50% HOME	| 20-35% HOME	| 0-20% HOME |
| Housing Cost Burden	| <24%	| 25-29%	| 30-34%	| 35-39%	| 40-49%	| 50%+ |
| Repair Needs | 0	| 1-2	| 3-4	| 5-6	| 7-8	| 9+ |
| Census Tract LMI Percentage	| <10%	| 10-19%	| 20-39%	| 40-59%	| 60-79%	| 80-100% |

## Weights

While the vulnerability index allows us to prioritize cases based on need, it should be weighted to balance out the criteria important to our program and help identify those most in need. For instance, there are multiple variables related to household earnings: income, housing cost burden, and the Census Tract LMI percentage. Giving these values equal weight would place an outsized importance on income, though people who qualify for the program must already meet the criteria for being low-to-moderate income. 

Note: If all criteria had equal weight distribution, each variable would receive a weight of .167 (~17%).

### Age – 0.30 (30%)
Age has been given the highest weight of all the criteria, due to the vulnerability from multiple angles and impact of housing condition on health.

-	Individuals who are elderly are unlikely to be able to carry out any repairs themselves.

-	Elderly individuals are typically on a fixed income, such as social security, that does not accommodate the cost of major home repairs.

-	Ensuring elderly individuals live in a healthy home allows them the opportunity to age in place, allowing them independence and preventing or delaying a move into a care facility.

### Repair Needs – 0.20 (20%)
By surveying applicants on various problems related to their home, we have gained an insight into the type of repairs needed by the individual. We can ensure that our funds are being used towards repairs that will have large improvements on the quality of life of the household, rather than applicants seeking minor or aesthetic-focused repairs.  Repair needs are self-reported at the time of intake.

### Assessed Value – 0.20 (20%)
Throughout the years the Shelby County Department of Housing has repaired homes through our rehabilitation program, there have been numerous instances of homes repaired which had high appraisal value, including some examples over $240,000.  We seek to prioritize homes with lower appraised values, as these homeowners likely have fewer opportunities to leverage debt with home equity loans and likely had more limited income to afford less expensive homes.

### Income – 0.15 (15%)
A person's income limits the repairs they can complete on their home. This criterion has been weighted slightly below the equal weight distribution due to the following two factors (Housing Cost Burden and Census Tract LMI Percentage), which are also related to income. 

### Housing Cost Burden – 0.10 (10%)
Someone who spends a large portion of their income towards housing costs (mortgage plus utilities) might not be able to save for repair costs. However, it is not advisable to overweight this criterion. As many of our clients are elderly and have lived in their home for many decades, many have already paid off their home and do not have a monthly mortgage payment. Similarly, a person who has inherited a home might have relatively low housing costs. We do not want to punish people for owning their home outright or inheriting a home. Individuals with a low housing cost burden might still have an income that makes repairs difficult to afford.

### Census Tract LMI Percentage – 0.05 (5%)
Prioritizing the Census tract’s Percentage of Low-Moderate Income households allows us to target repairs in communities that might need it the most. However, it has been given the lowest weight due to the following reasons:

-	Some communities might be excluded by overweighting this category. For instance, the department has completed extensive work in Census tract 216.20 in Collierville. This tract is sliced by a railroad tract near the northern perimeter. This tract has historically contained development south of the railroad that is low-income and majority Black. However, recent development north of the railroad has changed the demographics, dramatically increasing the median home value and incomes of the Census tract. The original community is still in need of assistance, and it would be unwise to exclude these households due to the new development.
    
-	Currently, the Low-Moderate Income dataset used is one provided by HUD, which uses data from the 2011-2015 American Community Survey. A new dataset is expected sometime in 2023. Thus, the current dataset is somewhat outdated and there exists the possibility that LMI tracts might change.
