---
title: "Income Regulations"
toc: true
page-layout: full
---

## Part 5 Changes {#sec-part-5-changes}

Section | Is HOME (Part 92) affected by Part 5 changes? 
---|---
Net Family Assets Definition ([§ 5.603](#def-net-family-assets)) | Yes, unless the participating jurisdiction chooses to calculate income using the IRS income definition. The value of a homeowner\'s principal residence is excluded under owner-occupied rehabilitation programs. Income or asset enhancements derived from the HOME-assisted project shall not be considered in calculating assets or annual income ([§ 92.203(c)(1)](#sec-92-203-c-1) and [(e)(1)](#sec-92-203-e-1)).
Annual Income Definition (§ 5.609(a)) | Yes, unless the participating jurisdiction uses IRS income definition under § 92.203(c)(2) ([§ 92.203(c)(1)](#sec-92-203-c-1)).
Annual Income Exclusions (§ 5.609(b)) | Yes, unless the participating jurisdiction uses IRS income definition under § 92.203(c)(2) ([§ 92.203(c)(1)](#sec-92-203-c-1)).
Annual Income Calculation & Reexaminations ([§ 5.609(c)](#sec-92-203-c)). | No, unless unit is subject to § 92.203(a)(1) or the participating jurisdiction accepts income determination under § 92.203(a)(2) (§ 92.203(a) & (f)).
Asset restriction (§ 5.618). | No |

## § 5.603 Definitions. {#sec-5-603}

### Net family assets {#def-net-family-assets}

(1) Net family assets is the net cash value of all assets owned by the family, after deducting reasonable costs that would be incurred in disposing real property, savings, stocks, bonds, and other forms of capital investment.

(2) In determining net family assets, PHAs or owners, as applicable, must include the value of any business or family assets disposed of by an applicant or tenant for less than fair market value (including a disposition in trust, but not in a foreclosure or bankruptcy sale) during the two years preceding the date of application for the program or reexamination, as applicable, in excess of the consideration received therefor. In the case of a disposition as part of a separation or divorce settlement, the disposition will not be considered to be for less than fair market value if the applicant or tenant receives consideration not measurable in dollar terms. Negative equity in real property or other investments does not prohibit the owner from selling the property or other investments, so negative equity alone would not justify excluding the property or other investments from family assets.

(3) Excluded from the calculation of net family assets are:

    (i) The value of necessary items of personal property;

    (ii) The combined value of all nonnecessary items of personal property if the combined total value does not exceed \$50,000 (which amount will be adjusted by HUD in accordance with the Consumer Price Index for Urban Wage Earners and Clerical Workers);

    (iii) The value of any account under a retirement plan recognized as such by the Internal Revenue Service, including individual retirement arrangements (IRAs), employer retirement plans, and retirement plans for self-employed individuals;

    (iv) The value of real property that the family does not have the effective legal authority to sell in the jurisdiction in which the property is located;

    (v) Any amounts recovered in any civil action or settlement based on a claim of malpractice, negligence, or other breach of duty owed to a family member arising out of law, that resulted in a family member being a person with a disability;

    (vi) The value of any Coverdell education savings account under section 530 of the Internal Revenue Code of 1986, the value of any qualified tuition program under section 529 of such Code, the value of any Achieving a Better Life Experience (ABLE) account authorized under Section 529A of such Code, and the value of any ''baby bond'' account created, authorized, or funded by Federal, State, or local government.

    (vii) Interests in Indian trust land;

    (viii) Equity in a manufactured home where the family receives assistance under 24 CFR part 982;

    (ix) Equity in property under the Homeownership Option for which a family receives assistance under 24 CFR part 982;

    (x) Family Self-Sufficiency Accounts; and

    (xi) Federal tax refunds or refundable tax credits for a period of 12 months after receipt by the family.

(4) In cases where a trust fund has been established and the trust is not revocable by, or under the control of, any member of the family or household, the trust fund is not a family asset and the value of the trust is not included in the calculation of net family assets, so long as the fund continues to be held in a trust that is not revocable by, or under the control of, any member of the family or household.

## § 5.609 Annual income. {#sec-5-609}

### Inclusions 

(a) Annual income includes, with respect to the family:

    (1) All amounts, not specifically excluded in paragraph (b) of this section, received from all sources by each member of the family who is 18 years of age or older or is the head of household or spouse of the head of household, plus unearned income by or on behalf of each dependent who is under 18 years of age, and

    (2) When the value of net family assets exceeds \$50,000 (which amount HUD will adjust annually in accordance with the Consumer Price Index for Urban Wage Earners and Clerical Workers) and the actual returns from a given asset cannot be calculated, imputed returns on the asset based on the current passbook savings rate, as determined by HUD.

### Exclusions

(b) Annual income does not include the following:

    (1) Any imputed return on an asset when net family assets total \$50,000 or less (which amount HUD will adjust annually in accordance with the Consumer Price Index for Urban Wage Earners and Clerical Workers) and no actual income from the net family assets can be determined.

    (2) The following types of trust distributions:

        (i) For an irrevocable trust or a revocable trust outside the control of the family or household excluded from the definition of net family assets under § 5.603(b):

            (A) Distributions of the principal or corpus of the trust; and
            (B) Distributions of income from the trust when the distributions are used to pay the costs of health and medical care expenses for a minor.

        (ii) For a revocable trust under the control of the family or household, any distributions from the trust; except that any actual income earned by the trust, regardless of whether it is distributed, shall be considered income to the family at the time it is received by the trust.

    (3) Earned income of children under the 18 years of age.

    (4) Payments received for the care of foster children or foster adults, or State or Tribal kinship or guardianship care payments.

    (5) Insurance payments and settlements for personal or property losses, including but not limited to payments through health insurance, motor vehicle insurance, and workers' compensation.

    (6) Amounts received by the family that are specifically for, or in reimbursement of, the cost of health and medical care expenses for any family member.

    (7) Any amounts recovered in any civil action or settlement based on a claim of malpractice, negligence, or other breach of duty owed to a family member arising out of law, that resulted in a member of the family becoming disabled.

    (8) Income of a live-in aide, foster child, or foster adult as defined in §§ 5.403 and 5.603, respectively.

    (9) 

        (i) Any assistance that section 479B of the Higher Education Act of 1965, as amended (20 U.S.C. 1087uu), requires be excluded from a family's income; and

        (ii) Student financial assistance for tuition, books, and supplies (including supplies and equipment to support students with learning disabilities or other disabilities), room and board, and other fees required and charged to a student by an institution of higher education (as defined under Section 102 of the Higher Education Act of 1965 (20 U.S.C. 1002)) and, for a student who is not the head of household or spouse, the reasonable and actual costs of housing while attending the institution of higher education and not residing in an assisted unit.

             (A) Student financial assistance, for purposes of this paragraph (9)(ii), means a grant or scholarship received from---

                 (1) The Federal government;

                 (2) A State, Tribe, or local government;

                 (3) A private foundation registered as a nonprofit under 26 U.S.C. 501(c)(3);

                 (4) A business entity (such as corporation, general partnership, limited liability company, limited partnership, joint venture, business trust, public benefit corporation, or nonprofit entity); or

                 (5) An institution of higher education.

             (B) Student financial assistance, for purposes of this paragraph (9)(ii), does not include---

                 (1) Any assistance that is excluded pursuant to paragraph (b)(9)(i) of this section;

                 (2) Financial support provided to the student in the form of a fee for services performed (e.g., a work study or teaching fellowship that is not excluded pursuant to paragraph (b)(9)(i) of this section);

                 (3) Gifts, including gifts from family or friends; or

                 (4) Any amount of the scholarship or grant that, either by itself or in combination with assistance excluded under this paragraph or paragraph (b)(9)(i), exceeds the actual covered costs of the student. The actual covered costs of the student are the actual costs of tuition, books and supplies (including supplies and equipment to support students with learning disabilities or other disabilities), room and board, or other fees required and charged to a student by the education institution, and, for a student who is not the head of household or spouse, the reasonable and actual costs of housing while attending the institution of higher education and not residing in an assisted unit. This calculation is described further in paragraph (b)(9)(ii)(E) of this section.

             (C) Student financial assistance, for purposes of this paragraph (b)(9)(ii) must be:

                 (1) Expressly for tuition, books, room and board, or other fees required and charged to a student by the education institution;

                 (2) Expressly to assist a student with the costs of higher education; or

                 (3) Expressly to assist a student who is not the head of household or spouse with the reasonable and actual costs of housing while attending the education institution and not residing in an assisted unit.

             (D) Student financial assistance, for purposes of this paragraph (b)(9)(ii), may be paid directly to the student or to the educational institution on the student's behalf. Student financial assistance paid to the student must be verified by the responsible entity as student financial assistance consistent with this paragraph (b)(9)(ii).

             (E) When the student is also receiving assistance excluded under paragraph (b)(9)(i) of this section, the amount of student financial assistance under this paragraph (b)(9)(ii) is determined as follows:

                 (1) If the amount of assistance excluded under paragraph (b)(9)(i) of this section is equal to or exceeds the actual covered costs under paragraph (b)(9)(ii)(B)(4) of this section, none of the assistance described in this paragraph (b)(9)(ii) of this section is considered student financial assistance excluded from income under this paragraph (b)(9)(ii)(E).

                 (2) If the amount of assistance excluded under paragraph (b)(9)(i) of this section is less than the actual covered costs under paragraph (b)(9)(ii)(B)(4) of this section, the amount of assistance described in paragraph (b)(9)(ii) of this section that is considered student financial assistance excluded under this paragraph is the lower of:

                     (i) the total amount of student financial assistance received under this paragraph (b)(9)(ii) of this section, or

                     (ii) the amount by which the actual covered costs under paragraph (b)(9)(ii)(B)(4) of this section exceeds the assistance excluded under paragraph (b)(9)(i) of this section.

    (10) Income and distributions from any Coverdell education savings account under section 530 of the Internal Revenue Code of 1986 or any qualified tuition program under section 529 of such Code; and income earned by government contributions to, and distributions from, ''baby bond'' accounts created, authorized, or funded by Federal, State, or local government.

    (11) The special pay to a family member serving in the Armed Forces who is exposed to hostile fire.

    (12) 

         (i) Amounts received by a person with a disability that are disregarded for a limited time for purposes of Supplemental Security Income eligibility and benefits because they are set aside for use under a Plan to Attain Self-Sufficiency (PASS);

         (ii) Amounts received by a participant in other publicly assisted programs which are specifically for or in reimbursement of out-of-pocket expenses incurred (e.g., special equipment, clothing, transportation, child care, etc.) and which are made solely to allow participation in a specific program;

         (iii) Amounts received under a resident service stipend not to exceed \$200 per month. A resident service stipend is a modest amount received by a resident for performing a service for the PHA or owner, on a part-time basis, that enhances the quality of life in the development.

         (iv) Incremental earnings and benefits resulting to any family member from participation in training programs funded by HUD or in qualifying Federal, State, Tribal, or local employment training programs (including training programs not affiliated with a local government) and training of a family member as resident management staff. Amounts excluded by this provision must be received under employment training programs with clearly defined goals and objectives and are excluded only for the period during which the family member participates in the employment training program unless those amounts are excluded under paragraph (b)(9)(i) of this section.

    (13) Reparation payments paid by a foreign government pursuant to claims filed under the laws of that government by persons who were persecuted during the Nazi era.

    (14) Earned income of dependent fulltime students in excess of the amount of the deduction for a dependent in § 5.611.

    (15) Adoption assistance payments for a child in excess of the amount of the deduction for a dependent in § 5.611.

    (16) Deferred periodic amounts from Supplemental Security Income and Social Security benefits that are received in a lump sum amount or in prospective monthly amounts, or any deferred Department of Veterans Affairs disability benefits that are received in a lump sum amount or in prospective monthly amounts.

    (17) Payments related to aid and attendance under 38 U.S.C. 1521 to veterans in need of regular aid and attendance.

    (18) Amounts received by the family in the form of refunds or rebates under State or local law for property taxes paid on the dwelling unit.

    (19) Payments made by or authorized by a State Medicaid agency (including through a managed care entity) or other State or Federal agency to a family to enable a family member who has a disability to reside in the family's assisted unit. Authorized payments may include payments to a member of the assisted family through the State Medicaid agency (including through a managed care entity) or other State or Federal agency for caregiving services the family member provides to enable a family member who has a disability to reside in the family's assisted unit.

    (20) Loan proceeds (the net amount disbursed by a lender to or on behalf of a borrower, under the terms of a loan agreement) received by the family or a third party (e.g., proceeds received by the family from a private loan to enable attendance at an educational institution or to finance the purchase of a car).

    (21) Payments received by Tribal members as a result of claims relating to the mismanagement of assets held in trust by the United States, to the extent such payments are also excluded from gross income under the Internal Revenue Code or other Federal law.

    (22) Amounts that HUD is required by Federal statute to exclude from consideration as income for purposes of determining eligibility or benefits under a category of assistance programs that includes assistance under any program to which the exclusions set forth in paragraph (b) of this section apply. HUD will publish a notice in the Federal Register to identify the benefits that qualify for this exclusion. Updates will be published when necessary.

    (23) Replacement housing ''gap'' payments made in accordance with 49 CFR part 24 that offset increased out of pocket costs of displaced persons that move from one federally subsidized housing unit to another Federally subsidized housing unit. Such replacement housing ''gap'' payments are not excluded from annual income if the increased cost of rent and utilities is subsequently reduced or eliminated, and the displaced person retains or continues to receive the replacement housing ''gap'' payments.

    (24) Nonrecurring income, which is income that will not be repeated in the coming year based on information provided by the family. Income received as an independent contractor, day laborer, or seasonal worker is not excluded from income under this paragraph, even if the source, date, or amount of the income varies. Nonrecurring income includes:

         (i) Payments from the U.S. Census Bureau for employment (relating to decennial census or the American Community Survey) lasting no longer than 180 days and not culminating in permanent employment.

         (ii) Direct Federal or State payments intended for economic stimulus or recovery.

         (iii) Amounts directly received by the family as a result of State refundable tax credits or State tax refunds at the time they are received.

         (iv) Amounts directly received by the family as a result of Federal refundable tax credits and Federal tax refunds at the time they are received.

         (v) Gifts for holidays, birthdays, or other significant life events or milestones (e.g., wedding gifts, baby showers, anniversaries).

         (vi) Non-monetary, in-kind donations, such as food, clothing, or toiletries, received from a food bank or similar organization.

         (vii) Lump-sum additions to net family assets, including but not limited to lottery or other contest winnings.

    (25) Civil rights settlements or judgments, including settlements or judgments for back pay.

    (26) Income received from any account under a retirement plan recognized as such by the Internal Revenue Service, including individual retirement arrangements (IRAs), employer retirement plans, and retirement plans for self-employed individuals; except that any distribution of periodic payments from such accounts shall be income at the time they are received by the family.

    (27) Income earned on amounts placed in a family's Family Self Sufficiency Account.

    (28) Gross income a family member receives through self-employment or operation of a business; except that the following shall be considered income to a family member:

         (i) Net income from the operation of a business or profession. Expenditures for business expansion or amortization of capital indebtedness shall not be used as deductions in determining net income. An allowance for depreciation of assets used in a business or profession may be deducted, based on straight line depreciation, as provided in Internal Revenue Service regulations; and

         (ii) Any withdrawal of cash or assets from the operation of a business or profession will be included in income, except to the extent the withdrawal is reimbursement of cash or assets invested in the operation by the family.

## § 92.203 Income determinations. {#sec-92-203}

### (a) Methods of determining annual income. {#sec-92-203-a}

The HOME program has income targeting requirements for the HOME program and for HOME projects. Therefore, the participating jurisdiction must determine each family is income eligible by determining the family's annual income.

(3) In all other cases, the participating jurisdiction must calculate annual income in accordance with paragraphs (b) through (e) of this section and calculate adjusted income in accordance with paragraph (f) of this section.

### (b) Required documentation for annual income calculations. {#sec-92-203-b}

(2) For all other families (i.e., homeowners receiving rehabilitation assistance, homebuyers, and recipients of HOME tenant-based rental assistance), the participating jurisdiction must determine annual income by examining at least 2 months of source documents evidencing annual income (e.g., wage statement, interest statement, unemployment compensation statement) for the family.

### (c) Defining income for eligibility. {#sec-92-203-c}

When determining whether a family is income eligible, the participating jurisdiction must use one of the following two definitions of ''annual income'':

[(1)](){#sec-92-203-c-1} Annual income as defined at §§ 5.609(a) and (b) of this title (except when determining the income of a homeowner for an owner-occupied rehabilitation project, the value of the homeowner's principal residence may be excluded from the calculation of net family assets, as defined in § 5.603 of this title);

[(2)](){#sec-92-203-c-2} Adjusted gross income as defined for purposes of reporting under Internal Revenue Service (IRS) Form 1040 series for individual Federal annual income tax purposes.

### (d) Using income definitions. {#sec-92-203-d}

The participating jurisdiction may use only one definition of annual income for each HOME-assisted program (e.g., downpayment assistance program) that it administers and only one definition for each rental housing project. A participating jurisdiction may use either of the definitions of ''annual income'' permitted in paragraph (c) of this section.

### (e) Determining family composition and projecting income. {#sec-92-203-e}

[(1)](){#sec-92-203-e-1} The participating jurisdiction must calculate the annual income of the family by projecting the prevailing rate of income of the family at the time the participating jurisdiction determines that the family is income eligible. Annual income includes income from all persons in the household, except live-in aides, foster children, and foster adults. Income or asset enhancement derived from the HOME-assisted project shall not be considered in calculating annual income. Families may use the certification process in § 5.618 of this title to certify that their net family assets are below the threshold for imputing income used in § 5.609(a)(2) of this title, as applicable. Families using the certification process in § 5.618 of this title that are homeowners applying for an owner-occupied rehabilitation project may also exclude the value of the homeowner's principal residence from the calculation of their Net Family Assets for purposes of the certification.

[(2)](){#sec-92-203-e-2} The participating jurisdiction is not required to re-examine the family's income at the time the HOME assistance is provided, unless more than six months has elapsed since the participating jurisdiction determined that the family qualified as income eligible.
