---
title: "Down Payment Assistance"
---

Shelby County's Down Payment Assistance (DPA) Program assists low and moderate income individuals in covering a portion of their down payment and closing costs associated with purchasing a home. The home that you buy may be either an existing home or a newly constructed home anywhere within the boundaries of Shelby County as long as the purchase price does not exceed \$300,000. Effective February 15, 2023, up to \$6,000 is available as a 3% fixed rate loan and repayment terms can extend up to 15 years (180 months).  Debt ratios must not exceed 45% total debt.

## Eligibility

- The purchaser must invest a minimum of \$500 of his/her own funds.
- The home being purchased must be located within Shelby County.
- Purchasers must be able to qualify for either THDA, FHA, VA, or Conventional Financing.
- Purchasers need a good credit history, stable employment, and  must complete a certified Homebuyer Education Class.
- You must also meet minimum and maximum income limit requirements by family size as shown in the chart below.

| Household Size | Income Limits |
|:---:|:---:|
| 2 or fewer | \$26,100 - \$85,990 |
| 3 or more | \$26,100 - \$98,888 |

## Questions

For more information contact the Shelby County Department of Housing at 901-222-7614 weekdays between 8:00 a.m. and 4:30 p.m. Ask to speak with a Down Payment Assistance Loan Counselor [Darren Bortters](mailto:Darren.W.Bortters@shelbycountytn.gov). A Counselor can answer any questions that you may have and will be able to provide you with further information on the Down Payment Assistance Program.
